# 그리드 백테스트 인수인계 (2026-08-21)

e2(EMA 정배열 눌림목) 종료 후 대안으로 검토한 **그리드 매매**의 검증 기록입니다.
현물 / 선물 1·2·3배를 같은 조건으로 비교했습니다.

스크립트: `scratchpad/grid_sim.py`
데이터: `scratchpad/sec30/` 85심볼 10일 (1초봉 → 1분봉 OHLC 로 집계)

---

## 1. 결론 먼저

**그리드는 이 데이터에서 작동합니다.** e2 와 달리 수수료를 넘는 우위가 있습니다.

| 모드 | 격자 | 간격% | 청산률 | 수익 중앙 | 거래수 | 최대낙폭 |
|---|---|---|---|---|---|---|
| 현물 폭±6% | 5 | 2.40 | **1.2%** | +6.75% | 45 | 16.4% |
| 선물1배 폭±6% | 5 | 2.40 | **1.2%** | +6.97% | 45 | 16.3% |
| 선물2배 폭±6% | 11 | 1.09 | 7.1% | +10.96% | 194 | 25.4% |
| **선물3배 폭±6%** | 16 | 0.75 | **11.8%** | **+15.44%** | 379 | 29.9% |

10일 기준입니다. **3배는 수익 중앙값이 1배의 2.2배인데 청산률은 10배입니다.**

**이것이 e2 와 결정적으로 다른 점입니다.** e2 는 수수료 전 우위가 0 이라
파라미터를 아무리 바꿔도 부호가 안 바뀌었습니다. 그리드는 격자 실현이익이
수수료를 확실히 넘습니다(3배 기준 +7.37 vs 수수료 0.40).

---

## 2. 이 잔고에서 가장 중요한 제약 — 최소주문금액

**자본 28 USDT 에서는 거래소 최소주문금액(5 USDT)이 격자수를 결정합니다.**

```
최대 격자수 = 자본 x 레버리지 / 5
```

| 모드 | 최대 격자수 | 폭±6% 일 때 간격 | 10일 거래수 |
|---|---|---|---|
| 현물 / 선물1배 | **5개** | 2.40% | 45 |
| 선물2배 | 11개 | 1.09% | 194 |
| 선물3배 | 16개 | 0.75% | 379 |

**저레버리지일수록 격자를 촘촘히 깔 수 없습니다.** 이것이 레버리지별 수익
차이의 주된 원인입니다. 3배가 1배보다 잘 버는 이유는 "레버리지 배수" 때문이
아니라 **격자를 3배 촘촘히 깔 수 있어 8배 더 자주 체결되기 때문**입니다.

자본이 커지면 이 제약이 풀립니다. 예를 들어 자본 100 USDT 면 1배로도 격자를
20개 깔 수 있어, 레버리지 없이 지금의 3배와 비슷한 체결 빈도가 나옵니다.
**즉 지금의 3배 선호는 자본 부족을 레버리지로 메우는 구조입니다.**

---

## 3. 현물 vs 선물 1배 — 차이가 거의 없습니다

| | 현물 | 선물1배 |
|---|---|---|
| 수익 중앙 | +6.75% | +6.97% |
| 수수료 | 0.2550 | 0.0510 |
| 펀딩비 | 0 | 0.0411 |
| 청산률 | 1.2% | 1.2% |

수수료는 현물이 5배 비싸지만(왕복 0.2% vs 0.04%), **격자가 5개뿐이라 거래수가
45건에 그쳐 절대 차이가 0.20 USDT(0.7%p)에 불과**합니다. 선물은 그 이득을
펀딩비로 절반 반납합니다.

**격자가 적을 때는 현물과 선물 1배가 사실상 같습니다.**
수수료 차이는 거래수가 많아질 때(=자본이 커지거나 레버리지를 올릴 때) 벌어집니다.

---

## 4. 레버리지 트레이드오프

폭±6% 기준 수익 분포입니다. 청산은 -100% 로 포함돼 있습니다.

| 모드 | 최저 | 25% | 중앙 | 75% | 최고 | 손실 심볼 |
|---|---|---|---|---|---|---|
| 현물 | -100.0 | -8.9 | +6.7 | +13.9 | +53.2 | 26/85 (31%) |
| 선물1배 | -100.0 | -8.2 | +7.0 | +14.6 | +55.5 | 25/85 (29%) |
| 선물2배 | -100.0 | -17.3 | +11.0 | +23.1 | +82.4 | 24/85 (28%) |
| 선물3배 | -100.0 | **-26.2** | +15.4 | +30.5 | +109.6 | 25/85 (29%) |

**손실 심볼 비율은 네 모드가 거의 같습니다(28~31%).** 레버리지가 바꾸는 것은
"얼마나 자주 지는가"가 아니라 **"질 때 얼마나 크게 지는가"** 입니다.
25% 분위가 -8.9% → -26.2% 로 3배 깊어집니다.

**청산률이 실질적인 비용입니다.**

| 모드 | 청산률 | 85심볼 중 |
|---|---|---|
| 현물 / 선물1배 | 1.2% | 1개 |
| 선물2배 | 7.1% | 6개 |
| 선물3배 | 11.8% | **10개** |

3배로 85개 심볼에 그리드를 돌리면 **10일 안에 10개가 전액 손실**입니다.
한 심볼에만 돌린다면 10일 안에 전액을 잃을 확률이 약 12% 라는 뜻입니다.

---

## 5. 범위 이탈 — 가장 큰 미해결 문제

| 폭 | 범위 밖에서 보낸 시간 |
|---|---|
| ±3% | 77~85% |
| ±6% | 60~71% |
| ±10% | 41~48% |

**폭 ±6% 로 잡으면 시간의 60~70% 를 범위 밖에서 보냅니다.**
범위를 벗어나면 그리드는 일하지 않습니다. 아래로 벗어나면 재고를 다 안은 채
평가손실만 커지고, 위로 벗어나면 재고를 다 팔고 현금으로 놉니다.

이 시뮬레이션은 **범위를 시작 시점에 고정하고 재설정하지 않습니다.**
실제 운용에서는 재설정(re-center)이 필수인데, 그때마다 수수료와 실현손실이
발생합니다. **재설정 규칙을 넣어 다시 재기 전에는 위 수익률을 그대로 믿으면
안 됩니다.** 폭 ±10% 가 이탈이 가장 적으면서 3배 수익도 ±6% 와 비슷한
(+15.37 vs +15.44) 것은 주목할 만합니다 — 청산률도 11.8% → 8.2% 로 낮습니다.

---

## 6. 첫 실행의 모델 결함 (기록용)

**첫 결과는 전 모드 마이너스였습니다(3배 -32.3%). 그것은 모델 오류였습니다.**

원인: 격자 매도 시 손익을 **보유 전체의 평균단가** 기준으로 계산했습니다.
하락 중에는 평단이 계속 올라가므로 격자가 맞물려도 손실로 기록됩니다.
격자 실현이익이 **-0.81** 이라는, 그리드에서 나올 수 없는 값이 나왔습니다.

수정: 실제 그리드봇 방식인 **짝짓기**로 바꿨습니다.
격자 i 에서 산 물량은 **격자 i+1 에서만** 팔고, 맞물릴 때마다 정확히
한 칸(간격 %)만큼 확정됩니다. 같은 격자 중복 매수도 막았습니다.

수정 후 격자 실현이익 **-0.81 → +2.76**(현물), **+7.37**(3배).

**교훈**: 그리드 백테스트에서 실현손익이 음수로 나오면 회계 방식을 먼저
의심하십시오. 전략이 아니라 모델 문제입니다.

---

## 7. 이 검증의 한계 — 반드시 읽으십시오

1. **1분봉 OHLC 로 경로를 근사**했습니다. 양봉은 시가→저가→고가→종가,
   음봉은 시가→고가→저가→종가로 지나갔다고 가정합니다.
   봉 안에서 격자를 여러 번 오가는 경우를 놓치므로 **체결 횟수가 실제보다
   적게 나옵니다**(결과가 보수적). 간격이 좁은 3배에서 영향이 가장 큽니다.
2. **범위 재설정이 없습니다.** 시작 시점 가격 기준으로 범위를 고정합니다.
   실제 운용의 핵심 변수가 빠져 있습니다.
3. **롱 전용**입니다. 중립(양방향) 그리드는 재지 않았습니다.
4. **단일 10일 구간**입니다. 워크포워드(시간 분할·심볼 분할)를 하지 않았습니다.
   **채택 전 반드시 분할 검증하십시오** — e2 에서 정한 프로젝트 기준입니다.
5. **펀딩비를 8시간당 0.01% 지불로 고정 가정**했습니다. 실제로는 심볼·시점별로
   다르고 받는 경우도 있습니다.
6. **체결 슬리피지 0** 가정입니다. 지정가라 합리적이지만, 급변동 시
   격자를 건너뛰는 경우가 반영되지 않았습니다.
7. **85심볼 동시 운용이 아니라 심볼별 독립 실행**입니다. 자본 28 USDT 를
   각 심볼에 전부 배정한 결과라, 실제로 여러 심볼에 나누면 심볼당 자본이
   줄어 **격자수가 더 줄어듭니다.**

7번이 특히 중요합니다. **28 USDT 를 3심볼에 나누면 심볼당 9.3 USDT 이고,
3배라도 격자가 5개까지 떨어집니다.** 지금 표의 3배 성적은 한 심볼에 전액을
넣었을 때의 값입니다.

---

## 8. 권고

**단기(지금 자본에서)**

- **폭 ±10% 를 우선 검토**하십시오. ±6% 대비 수익은 같은데(3배 +15.37 vs
  +15.44) 청산률이 11.8% → 8.2%, 범위 이탈이 60% → 41% 로 개선됩니다.
- **심볼 분산은 오히려 불리합니다.** 자본이 쪼개져 격자수가 줄어듭니다.
  1~2 심볼 집중이 이 자본 규모에서는 합리적입니다. 다만 그만큼 단일 심볼
  리스크가 커집니다.
- **레버리지는 사용자 판단입니다.** 3배의 대가는 명확합니다 —
  수익 중앙 2.2배, 청산 확률 10배(1.2% → 11.8%).

**중기**

- 자본이 100 USDT 를 넘으면 **1배로도 격자 20개**가 가능합니다.
  그 시점에는 레버리지 없이 지금의 3배와 비슷한 체결 빈도가 나옵니다.
  **자본 증가가 레버리지를 대체합니다.**

**봇을 만들기 전에 반드시**

1. **범위 재설정 규칙을 넣고 다시 측정**하십시오. 이게 없으면 위 수익률은
   실전과 무관합니다.
2. **워크포워드**(시간 전/후반, 심볼 홀/짝)를 돌리십시오. 넷 다 플러스여야
   합니다.
3. **1초봉으로 상위 설정만 재검증**하십시오. 1분봉 근사가 체결을
   과소평가하므로 실제는 더 좋을 수 있지만, 확인해야 합니다.

---

## 9. e2 에서 가져올 것 (전략 무관, 재사용)

`scripts/scalp_bot_e2.py` 에 만들어 둔 안전·관측 장치는 그대로 이식하십시오.
전략과 무관하고 오늘 전부 실사고에서 나온 것들입니다.

| 장치 | 왜 |
|---|---|
| 봇 중복 실행 방지 (`acquire_bot_lock`) | e2 가 6개 동시 실행돼 각자 주문을 냈다 |
| 원장↔거래소 자동 대조 (`ledger_vs_exchange`) | 손실 19건 누락으로 승률이 14%p 부풀었다 |
| 외부청산 원장 기록 (`record_external_close`) | 거래소가 청산하면 봇이 기록을 안 남겼다 |
| 수량 정본화 (`live_position_qty`) | 내부 누적이 277,809 로 폭주했다(실제 24,232) |
| 손절 미보호 시간 상한 | 무한 재시도가 무보호 포지션을 방치했다 |

**그리드는 승률이 90%대로 나와 착시가 e2 보다 강합니다.**
격자 실현 수익만 보면 하락 추세에서도 계속 플러스입니다.
**반드시 미실현 포함 총자산으로 보고, 최대 낙폭을 함께 표시하십시오.**

---

## 10. 재현 방법

```bash
.venv312/Scripts/python.exe scratchpad/grid_sim.py <scratchpad 경로>
```

주요 상수는 파일 상단에 있습니다.

| 상수 | 현재값 | 의미 |
|---|---|---|
| `CAPITAL` | 28.0 | 심볼당 배정 자본 |
| `MIN_NOTIONAL` | 5.0 | 거래소 최소 주문 명목 |
| `MODES` | 4종 | (라벨, 레버리지, 편도수수료, 펀딩적용) |
| `WIDTHS` | 3/6/10% | 범위 폭 |
| `FUND_PER_8H` | 0.0001 | 펀딩비 가정 |

현물 수수료는 0.10%(BNB 할인 없음)로 잡았습니다. 계좌에 BNB 가 사실상
없어서(0.00000085) 할인을 못 받는 상태를 반영한 것입니다.
**BNB 를 소액 보유하면 현물 수수료가 0.075% 로 내려갑니다.**

---

# 11. 정정 — 앞 문서의 두 가지 오류

자본 규모별 추가 측정(`scratchpad/grid_capital.py`)에서 **§2 와 §8 의 서술이
틀렸음이 드러났습니다.**

## 오류 1 — "3배가 잘 버는 이유는 격자를 촘촘히 깔 수 있어서"

**틀렸습니다.** 총 격자수익은 **간격과 거의 무관**합니다.

| 현물 | 간격 | 거래수 | 거래수x간격 | 수익 |
|---|---|---|---|---|
| ±3% | 1.20% | 92 | 110 | +6.75% |
| ±6% | 2.40% | 45 | 108 | +6.75% |
| ±10% | 4.00% | 27 | 108 | +5.69% |

**거래수 × 간격이 일정합니다.** 촘촘히 깔면 자주 체결되는 만큼 한 번에 버는
금액이 작아져 상쇄됩니다. 자본 규모별 측정이 이를 다시 확인했습니다.

| 자본 | 격자 | 간격% | 거래수 | 수익 중앙 |
|---|---|---|---|---|
| 9.33 | 5 | 4.00 | 27 | **+17.70%** |
| 14.00 | 8 | 2.50 | 69 | +17.31% |
| 28.00 | 16 | 1.25 | 247 | +15.37% |
| 50.00 | 30 | 0.67 | 831 | +13.75% |
| 100~500 | 30 | 0.67 | 831 | +13.75% |

**격자를 늘릴수록 자본 대비 수익률이 오히려 조금씩 떨어집니다**(+17.70 → +13.75).
거래가 30배 늘어도 수익은 늘지 않고 수수료만 더 냅니다.

**따라서 3배의 이점은 격자수가 아니라 명목(자본 x 레버리지)입니다.**
같은 이유로 자본 50 USDT 이상에서는 격자수 상한(30)에 걸려 수익률이 평평합니다.

## 오류 2 — "심볼 분산은 오히려 불리하다"

**틀렸습니다.** 분산은 수익을 조금 깎는 대신 **파산 위험을 없앱니다.**

총자본 28 USDT 를 K개 심볼에 나눴을 때(심볼별 결과를 무작위 K개씩 3,000회 조합):

| 구성 | 심볼당 자본 | 수익 중앙 | 최저 5% | **전액손실 확률** |
|---|---|---|---|---|
| **1심볼 몰빵** | 28.00 | **+15.37%** | **-100.00%** | **9.1%** |
| 2심볼 분산 | 14.00 | +12.23% | -58.15% | 0.5% |
| 3심볼 분산 | 9.33 | +6.85% | -48.26% | **0.0%** |

몰빵의 중앙값이 높아 보이는 것은 **분포가 극단적으로 치우쳐 있기 때문**입니다.
중앙값은 +15% 인데 9.1% 확률로 전액을 잃습니다.

---

# 12. 몰빵 판단 — 반복하면 파산이 확정적입니다

10일을 1회로 보고 반복 운용했을 때의 생존 확률입니다.

| 구성 | 1회 파산확률 | 10회 생존 | 20회 생존 | 30회 생존 |
|---|---|---|---|---|
| **1심볼 몰빵** | 9.1% | **38.5%** | **14.8%** | **5.7%** |
| 2심볼 분산 | 0.5% | 95.1% | 90.5% | 86.0% |
| 3심볼 분산 | 0.1% | 99.5% | 99.0% | 98.5% |

**몰빵으로 100일(10회)을 돌리면 살아남을 확률이 38.5% 입니다.**
300일이면 5.7% 입니다.

복리의 핵심은 **생존**입니다. 한 번의 -100% 는 그 이전의 모든 수익을 지웁니다.
중앙값 +15% 와 +6.85% 의 차이는, 파산 확률 9.1% 와 0% 의 차이 앞에서 무의미합니다.

**결론: 자본 500 USDT 미만에서 몰빵은 권하지 않습니다.**
자본이 작다는 것이 몰빵의 근거가 되지 못합니다. 오히려 반대입니다 —
작은 자본일수록 한 번 잃으면 복구할 수단이 없습니다.

**최소 2심볼, 가급적 3심볼 분산**을 권합니다.
자본 28 USDT / 3배 / 3심볼이면 심볼당 9.33 USDT, 격자 5개가 확보됩니다.
§11 에서 확인했듯 **격자 5개는 격자 30개와 자본 대비 수익률이 같습니다**
(오히려 5개가 조금 낫습니다). 분산의 수익 손실은 격자수가 아니라
**심볼 분포의 평균 회귀** 때문입니다.

## 레버리지를 낮추는 것과 분산 중 무엇이 먼저인가

| 방법 | 수익 중앙 | 파산확률 |
|---|---|---|
| 3배 1심볼 | +15.37% | 9.1% |
| 3배 3심볼 | +6.85% | ~0% |
| 1배 1심볼 (§4) | +7.0% | 1.2% |

**3배 3심볼과 1배 1심볼의 수익이 거의 같습니다**(+6.85 vs +7.0).
파산확률은 3배 3심볼이 더 낮습니다. 즉 **레버리지를 낮추는 것보다
분산하는 편이 같은 수익에서 더 안전합니다.**

---

# 13. 다음 검증 — 심볼 자동 회전

사용자 제안: 자본이 작으니 **그리드가 잘 되는 심볼로 자동 이동**한다.

**주의**: 이 프로젝트에서 심볼 선별은 e1·e2 에서 **어떤 기준으로도 기각**됐습니다.
방향성 우위가 심볼별로 지속되지 않았기 때문입니다.

**다만 그리드는 다를 수 있습니다.** 그리드가 먹는 것은 방향이 아니라
"범위 안에서 얼마나 오가느냐"이고, 이는 심볼의 변동성 성격이라 지속될 수
있습니다. 범위 이탈이 41~48% 인 것도 심볼 선택으로 줄일 여지를 시사합니다.

**측정할 것 — 지속성이 전부입니다.**

1. 전반 5일 그리드 수익 vs 후반 5일 그리드 수익의 **순위 상관**
   - 상관이 있으면 회전이 작동한다
   - 없으면 e1·e2 와 같은 노이즈다
2. 상위 K심볼만 골랐을 때 vs 무작위 K심볼의 성적 차이
3. 회전 비용(범위 재설정 시 실현손실 + 수수료)을 차감한 뒤에도 남는가

**이 검증 없이 회전 로직을 만들지 마십시오.**
e2 에서 네 축을 다 뒤진 뒤에야 우위가 0 임을 알았던 실수를 반복하게 됩니다.

---

# 14. e3 실전 전 테스트 보강 (2026-08-21)

그리드 봇 `scripts/scalp_bot_e3.py` 의 **실전 투입 전 최소 검증**을 보강했습니다.
기존에 있던 재센터링 / 최소주문금액 실패 / 드라이런 체결 테스트는 그대로 두고
그 위에 세 갈래를 추가했습니다.

**스크립트는 수정하지 않았습니다.** `handle_global_stop` 이 이미 함수로
분리돼 있어 리팩터링이 필요 없었습니다.

## 추가한 테스트

### 1) `--resume` 상태 복구 (4건)

- `save_state` → `load_state` 왕복에서 기본 필드가 복원되는지
  (symbol, center_price, levels, qty_per_rung, held_buy_rungs,
  realized_grid_profit_est, reset_count)
- **`wallet_balance_start` 유지** — 이게 깨지면 손실 컷 기준선이 재시작마다
  리셋돼 손실 컷이 영영 안 걸린다 (e2 에서 `--max-hold-sec` 가 같은 이유로
  무력화됐던 전례가 있다)
- `buy_orders` / `sell_orders` 가 그대로 유지되고, 복구본이 바로 `GridState`
  입력으로 쓸 수 있는지
- 파일이 없거나 깨졌을 때 `None` 반환

### 2) `GLOBAL_STOP` 손실 컷 (5건)

- 기준 위에서는 발동하지 않고 주문·포지션·상태파일을 건드리지 않는다
- 발동 시 매수·매도 주문을 모두 취소한다
- **`live=False` 면 시장가 청산을 하지 않는다** (드라이런에서 실주문 방지)
- **`live=True` 면 `flatten_position` 이 호출된다**
- **종료 직전 `save_state` 가 실제로 파일을 쓴다** — 빠지면 재개 시 마지막
  사이클이 통째로 사라진다
- 취소가 예외를 던져도 청산과 저장까지 도달한다

### 3) `process_live_fills` 부분체결·미응답 (6건)

| 주문 상태 | 기대 동작 | 검증 |
|---|---|---|
| 조회 실패(예외) | 주문 유지, 재고 불변 | O |
| 응답은 왔으나 `None` | 주문 유지, 재고 불변 | O |
| `PARTIALLY_FILLED` | 주문 유지, 재고 불변, 수익 0 | O |
| `FILLED` (매수) | 주문 제거, `held_buy_rungs` 에 편입 | O |
| `FILLED` (매도) | 주문 제거, 재고 해제, 수익 계상 | O |
| 셋이 섞임 | 예외 없이 전 주문 조회, 체결분만 반영 | O |

**핵심은 "체결이 아닌 것을 체결로 오인하지 않는가"** 입니다.
조회 실패나 부분체결을 체결로 잡으면 **없는 재고를 만들고**, 그 재고에 대해
매도 주문을 걸어 `reduceOnly` 거부나 의도치 않은 숏이 발생합니다.

## 현재 한계 — 테스트로 고정해 두었습니다

`test_resume_does_not_reconcile_orders_with_exchange`

**`--resume` 에는 거래소 대조가 없습니다.** `load_state` 는 저장된 주문을
그대로 믿고, 거래소를 조회하지 않습니다. 그래서

- 봇이 죽어 있는 동안 **체결·취소된 주문**을 살아 있다고 보고 그 칸을 건너뛴다
- 거래소에 남아 있는데 상태 파일에 없으면 **같은 칸에 주문을 또 낸다**

이 테스트는 그 한계를 명시적으로 고정합니다. 대조 로직을 넣으면 테스트가
깨지고, 그때 갱신하면 됩니다. **실전 재개 전에는 거래소 미체결 주문을
수동으로 확인하십시오.**

## 결과

```
tests/test_scalp_bot_e3.py   24 passed
전체 스위트                  818 passed, 26 subtests passed
```

기존 테스트 4건 + 추가 15건 + 헬퍼로 커버되는 케이스 포함 24건입니다.

## 수정 파일

- `tests/test_scalp_bot_e3.py` (117 → 498줄, 기존 테스트 보존)
- `scripts/scalp_bot_e3.py` — **변경 없음**

---

# 15. 텔레그램 격자 뷰 추가 (2026-08-21)

바이낸스 그리드 화면처럼 **격자를 사다리로 보는 뷰**를 붙였습니다.
기존에는 숫자 요약(`summarize_status`)만 있어서 어느 칸이 채워졌는지 알 수 없었습니다.

## 버튼

하단 고정 메뉴 맨 위에 **🪜 e3격자** 를 추가했습니다.

```
🪜 e3격자
📊 e3상태    📈 e3브리핑
⏸ e3정지     ▶️ e3재개
🛑 e3전량정리
```

## 출력 예

```
[e3 격자] SOLUSDT  가동중
  8 112.000000 ·
  7 109.000000 ·
  6 106.000000 ·
  5 103.000000 ·
  4 100.000000 ○ 매도대기
  3  97.000000 ● 보유  ◀ 현재가
  2  94.000000 ● 보유
  1  91.000000 ◇ 매수대기
  0  88.000000 ◇ 매수대기

현재가 98.600000
범위 88.000000 ~ 112.000000 (중심 100.000000)
보유 2/9칸  대기 매수2 매도1
격자 실현(추정) +0.123400 USDT
자산 28.3100 (시작 28.0000, +0.3100)
재센터링 2회

※ 격자 실현은 맞물린 짝만 센 값입니다. 보유 중인 칸의
   평가손익은 '자산' 쪽에 반영됩니다.
```

기호는 호가창과 같은 방향(위가 고가)입니다.

| 기호 | 뜻 |
|---|---|
| ● | 보유 — 그 칸에서 매수 체결됨, 위 칸에 매도가 걸려 있다 |
| ○ | 매도 대기 |
| ◇ | 매수 대기 |
| · | 비어 있음 |
| ◀ | 현재가 위치 |

## 설계에서 신경 쓴 것

**격자가 많으면 창을 잘라 보여줍니다.** 30개를 전부 찍으면 텔레그램에서
읽을 수 없습니다. 현재가 주변 21칸(기본값)만 보여주고
`위로 N칸 생략` / `아래로 N칸 생략` 을 표시합니다.

**범위 이탈을 표시합니다.** 현재가가 범위를 벗어나면 `⚠ 범위 이탈` 이 붙습니다.
백테스트에서 시간의 40~60% 가 범위 밖이었으므로 자주 보게 될 표시입니다.

**착시 경고를 뷰에 고정했습니다.** 그리드는 격자 실현만 보면 하락장에서도
계속 플러스로 보입니다. e2 에서 원장이 손실을 빠뜨려 승률 59.7% 로 보였던 것과
같은 결과인데, 그리드는 코드가 멀쩡해도 그렇게 보입니다.
그래서 **격자 실현과 자산 변화를 나란히 놓고**, 실현이 짝 맞은 것만 센 값이라는
문구를 항상 출력합니다. 이 문구가 사라지지 않도록 테스트로 고정했습니다.

## 테스트 (10건 추가)

- 칸별 상태 표기(보유/매도대기/매수대기/빈칸)
- 위가 고가인 정렬
- 현재가 커서가 올바른 칸에 붙는지 (98.6 → rung3)
- 범위 이탈 표시 유무
- 격자 31개일 때 창 자르기 + 현재가가 창 안에 남는지
- 합계 표기(보유 n/전체, 대기 매수/매도, 격자 실현, 자산 변화)
- **착시 경고 문구 존재**
- 빈 격자 처리
- 일시정지 표기
- 버튼 배선

```
tests/test_scalp_bot_e3.py   34 passed
전체 스위트                  828 passed, 26 subtests passed
```

## 수정 파일

- `scripts/scalp_bot_e3.py` — `render_grid_view()` 추가, 버튼 1개와 핸들러 배선
- `tests/test_scalp_bot_e3.py` — 뷰 테스트 10건 추가

---

# 16. 넓은 후보군 자동선정 + 3슬롯 포트폴리오 E3 (2026-08-20)

사용자 요청:

- `XRPUSDT` 같은 고정 1심볼만 보지 말 것
- `PEPE`처럼 **저가 알트**도 후보군에 넣을 것
- `슬롯 3개`
- `총 자산 100% 운용`
- 심볼은 실시간 변동성에 맞춰 **빠르게 순환**

## 구현 방향

기존 `scripts/scalp_bot_e3.py` (단일 심볼 라이브 봇)는 **그대로 유지**합니다.
이미 라이브 포지션을 물고 있어, 그 파일을 바로 다중 슬롯 구조로 갈아엎으면
재시작 시 기존 그리드를 잃을 위험이 커지기 때문입니다.

대신 **별도 스크립트**를 추가했습니다.

- `scripts/scalp_bot_e3_portfolio.py`

이 스크립트는 단일 `CycleState` 대신 **슬롯 3개**를 독립적으로 돌립니다.

## 후보군 자동선정

고정 후보 6개 하드코딩을 버리고, **USDT-M Perpetual 전체**에서 상위 거래량 심볼을
넓게 읽습니다.

1. `get_active_usdt_perpetual_symbols(limit=60)` 으로 24h 거래대금 상위 60개를 읽는다
2. 각 심볼마다 아래 점수를 계산한다

| 항목 | 방향 |
|---|---|
| 최근 180분 박스 폭(`width_pct`) | 넓을수록 가점 |
| 최근 1분 절대 변동 평균(`mean_abs_1m_pct`) | 높을수록 가점 |
| 최근 60분/180분 방향 수익률 절대값 | 추세가 강할수록 감점 |
| 호가 스프레드(`spread_pct`) | 넓을수록 감점 |
| **저가 알트 보너스** (`price < 0.8`) | 가점 |
| 현재 자본/레버리지로 `grid_count` 를 최소주문금액 이상으로 깔 수 있는가 | 못 깔면 탈락 |

즉 후보군은 이제 `XRP, DOGE, ADA` 같은 중대형 알트뿐 아니라
`1000PEPEUSDT` 처럼 **작은 자본으로도 격자를 만들기 쉬운 심볼**이 자동으로
상위로 올라올 수 있습니다.

핵심 구현은 `scripts/scalp_bot_e3.py` 의 다음 헬퍼에 있습니다.

- `score_candidate_symbol()`
- `rank_candidate_symbols()`

## 3슬롯 100% 운용 구조

새 포트폴리오 스크립트는 총 자산을 슬롯 수로 나눠 씁니다.

기본:

- `--slots 3`
- `--capital-usage 1.0`

이면 슬롯당 배분은 사실상

- 슬롯1: 33.33%
- 슬롯2: 33.33%
- 슬롯3: 33.34%

로 나뉩니다.

각 슬롯은 독립적으로:

- 심볼 1개
- `±10%`
- `5격자`
- `3배`

를 가지며, 자체 `CycleState` 를 유지합니다.

## 순환(회전) 규칙

빠르게 순환하되, 수수료만 내고 왔다 갔다 하지 않도록 **이중 조건**을 둡니다.

- 점수 평가 주기: `5분` (`--score-eval-sec 300`)
- 같은 슬롯 최소 유지 시간: `20분` (`--min-switch-interval-sec 1200`)
- 즉시 교체: 현재 심볼이 범위를 벗어난 경우
- 일반 교체: 새 후보 점수가 현재 심볼보다 `15점` 이상 높을 때

즉 “5분마다 후보를 보되, 아무 이유 없이 계속 갈아타지는 않는다”가 설계 의도입니다.

## 상태/파일

포트폴리오형 E3 상태는 별도 파일을 씁니다.

- 상태: `logs/e3_portfolio_state.json`
- 로그: `logs/e3_portfolio_run.log`

기존 단일 라이브 E3가 쓰는

- `logs/scalp_bot_e3_state.json`

과 **완전히 분리**됩니다.

## 텔레그램

포트폴리오형 E3도 기존 `Tg` 를 그대로 재사용합니다.
현재는 최소한의 `상태/브리핑`은 되지만, 슬롯별 상세 격자 뷰는 아직 단일 E3만큼
풍부하지 않습니다.

## 테스트

추가:

- `tests/test_scalp_bot_e3_portfolio.py`

현재는 최소 수준:

- 중복 심볼 없는 선택 (`pick_symbols`)
- 빈 슬롯 요약

포트폴리오 전체 라이브 시뮬 테스트는 아직 얕습니다. **실전 전 반드시 드라이런으로
슬롯 교체/범위 이탈/손실 컷을 추가 검증해야 합니다.**

```
tests/test_scalp_bot_e3.py
tests/test_scalp_bot_e3_portfolio.py
  -> 49 passed
```

## 매우 중요한 운영 주의

### 1. 단일 E3 라이브와 포트폴리오 E3를 동시에 켜지 마십시오

둘 다 같은 선물 계좌를 사용합니다.
특히 같은 심볼을 동시에 잡으면 주문이 서로 꼬입니다.

### 2. 현재 라이브 `XRPUSDT` 단일 E3는 별도 관리 중

2026-08-20 기준 단일 E3는 이미 실제 주문/포지션을 들고 있습니다.
포트폴리오형 E3를 바로 실전 전환하려면, 먼저 단일 E3를 평탄화한 뒤
전환해야 합니다.

### 3. 재시작 안전성은 단일 E3 쪽이 먼저 보강됨

단일 E3는 `--resume` 에서 거래소 open order 를 읽어:

- 같은 rung 중복 주문 취소
- 현재 격자에 없는 stale 주문 취소
- 남은 주문/보유를 상태 파일에 다시 채택

이 경로를 통과합니다.

포트폴리오형 E3는 아직 이 수준까지 다듬지 않았습니다.
즉 **지금 당장 실전 전환 우선순위는 단일 E3 > 포트폴리오 E3** 입니다.

## 수정 파일

- `scripts/scalp_bot_e3.py` — 후보군 점수화/랭킹 헬퍼 추가
- `scripts/scalp_bot_e3_portfolio.py` — 신규, 3슬롯 100% 포트폴리오 E3
- `tests/test_scalp_bot_e3_portfolio.py` — 신규, 최소 헬퍼 테스트

---

# 16. `ensure_grid_orders` 검증 (2026-08-21)

§14 에서 **주문을 실제로 내는 경로가 통째로 미검증**이라고 지적했던 부분을
덮었습니다. `ensure_grid_orders` 는 e3 에서 돈을 움직이는 유일한 함수입니다.

**코덱스가 같은 파일로 TP/SL 작업 중이라 스크립트는 건드리지 않았습니다.**
테스트만 추가했고, 발견한 한계는 고치지 않고 아래에 기록합니다.

## 확인된 동작 (10건 추가, 46건 통과)

| 검증 | 왜 중요한가 |
|---|---|
| 드라이런에서 실주문 없음, 가짜 id 는 음수 | 실주문 id 와 섞이면 상태 추적이 깨진다 |
| 매수 `reduceOnly=False` / 매도 `reduceOnly=True` | 뒤바뀌면 재고 없이 숏이 열린다 |
| 매도는 **보유 칸 바로 위에만** | 보유 없는 칸에 걸면 `-2022 ReduceOnly 거부` |
| 보유가 없으면 매도를 아예 안 건다 | 같은 이유 |
| **두 번 호출해도 중복 주문 없음** | e2 에서 손절주문이 REUSDT 3건·XLMUSDT 2건 중복으로 쌓였다 |
| 이미 보유한 칸에 추가 매수 안 함 | 한 칸에 재고가 두 번 쌓인다 |
| 현재가 아래 칸에만 매수 | 격자 방향이 뒤집히면 즉시 체결된다 |
| 거래소 응답 id 를 그대로 기록 | 조회·취소가 불가능해진다 |
| 수량·가격이 state 에서 전달 | `qty_per_rung` 오류가 전 칸에 번진다 |

## 발견한 한계 — 한 칸 거부가 봇 전체를 죽입니다

`place_limit_order` 에 예외 처리가 없습니다. 한 칸이 거래소에 거부되면
`ensure_grid_orders` 가 그 자리에서 중단되고 예외가 `main` 루프까지 올라갑니다.

**다만 상태 오염은 없었습니다.** 이건 제가 우려했던 것과 달랐습니다.

- 실패한 칸은 `state.buy_orders` 에 기록되지 않는다 (유령 주문 없음)
- 실패 이전 성공분은 거래소에 나간 것과 `state` 기록이 정확히 일치한다

`test_order_failure_does_not_record_ghost_order` 가 이 동작을 고정합니다.
재시도나 칸 단위 격리를 넣으면 이 테스트가 깨지고, 그때 갱신하면 됩니다.

**실전 전 판단이 필요한 지점입니다.** 지금 구조에서는 일시적 거부
(`-2022`, `-1111` 정밀도, 레이트리밋) 하나로 봇이 종료됩니다.
그리드는 매 사이클 여러 칸에 주문을 내므로 거부를 만날 확률이 e2 보다 높습니다.

## 남은 미검증 (실전 전 확인 권장)

| 함수 | 상태 |
|---|---|
| `place_limit_order` | 가격 반올림·인자 조립이 직접 검증되지 않음(간접 커버) |
| `quantity_for_rung` | 미검증 |
| `main` | 루프 전체 미검증 |
| `acquire_bot_lock` | e2 에서는 검증됨, e3 사본은 미검증 |

## 텔레그램 격자 뷰 반영 주의

**§15 의 🪜 e3격자 버튼은 봇을 재시작해야 보입니다.**
메뉴는 기동 시 한 번만 전송되므로, 버튼 추가 전에 뜬 프로세스는
`/e3` 를 눌러도 옛 메뉴만 다시 보냅니다.

- e3 프로세스 기동: 01:10:34
- 버튼 추가(파일 수정): 01:22:10

**코덱스의 TP/SL 작업이 끝난 뒤 한 번에 재시작하는 것을 권합니다.**
관측용 기능이라 급하지 않고, 미완성 주문 로직이 실거래에 올라가면
문제가 생겼을 때 원인 분리가 어렵습니다.

## 테스트 현황

```
tests/test_scalp_bot_e3.py   46 passed
```

| 묶음 | 건수 |
|---|---|
| 기존(재센터링·최소주문·드라이런 체결) | 4 |
| `--resume` 상태 복구 | 4 |
| `GLOBAL_STOP` 손실 컷 | 5 |
| `process_live_fills` 부분체결·미응답 | 6 |
| 격자 사다리 뷰 | 10 |
| **`ensure_grid_orders` 주문 배치** | **10** |
| 기타(헬퍼 경유) | 7 |

## 수정 파일

- `tests/test_scalp_bot_e3.py` (34 → 46건)
- `scripts/scalp_bot_e3.py` — **이번 작업에서는 변경 없음**

## §17 XRPUSDT 종료 + 재시작 제외 (2026-08-20)

- `XRPUSDT` 단일 E3는 2026-08-20에 수동 종료함.
- 종료 시점 처리:
  - 미체결 주문 3개 취소 확인
  - 보유 포지션 0 확인
  - `logs/scalp_bot_e3_bot_pid.json` 삭제
  - 활성 상태 파일 `logs/scalp_bot_e3_state.json` 을 `logs/scalp_bot_e3_state.closed_xrp_2026-08-20.json` 으로 이동
  - 추가 백업 `logs/scalp_bot_e3_state.xrp_exit_backup.json` 보존
- 재시작 규칙:
  - 포트폴리오 E3는 `--exclude-symbols` 기본값을 `XRPUSDT` 로 둠.
  - 즉, 별도 지정 없이 재기동하면 후보 선정에서 리플은 자동 제외됨.
  - 다른 제외 심볼이 필요하면 `--exclude-symbols XRPUSDT,AAAUSDT,BBBUSDT` 형태로 확장 가능.

## §18 주문 거부 격리 + 정적 심볼 필터 (2026-08-20)

- `scripts/scalp_bot_e3.py`
  - `try_place_limit_order()` 추가.
  - 한 칸 주문이 거래소에서 거부돼도(`-2022`, 정밀도, 일시 오류 등) 그 칸만 건너뛰고 나머지 칸 주문은 계속 진행.
  - 실패한 칸은 state 에 기록하지 않고 `PLACE_ORDER_FAILED` 원장 이벤트만 남김.
  - 의미:
    - 예전: 한 칸 거부 -> `ensure_grid_orders()` 예외 전파 -> 메인 루프 종료 가능
    - 지금: 한 칸 거부 -> 그 칸만 비워두고 루프 지속

- `place_limit_order`, `quantity_for_rung` 직접 테스트 추가.
  - 가격 반올림, LONG/SHORT 방향 매핑, `reduceOnly`, `max_notional` 전달을 고정.

- 후보 선정 규칙 강화:
  - 여전히 `get_active_usdt_perpetual_symbols(limit=N)` 으로 **24시간 거래대금 상위**만 우선 스캔.
  - 그 안에서도 너무 멈춘 코인은 탈락시킴.
  - 기본 탈락 기준:
    - `width_pct < 4.0`
    - `mean_abs_1m_pct < 0.08`
    - `spread_pct > 0.12`
  - 즉 “그리드에 필요한 왕복성은 없고, 체결만 느린 코인”을 기본적으로 후보에서 제외.

- `scripts/scalp_bot_e3_portfolio.py`
  - 새 문턱값 CLI 추가:
    - `--min-width-pct`
    - `--min-mean-abs-1m-pct`
    - `--max-spread-pct`
  - 기본값은 위와 동일.

- 테스트:
  - `tests/test_scalp_bot_e3.py`
    - 주문 실패 격리 후에도 유령 주문이 남지 않는지
    - 나머지 칸 주문이 계속 진행되는지
    - 느린 코인/넓은 스프레드 코인이 후보에서 빠지는지
- 현재 직접 재검증 결과:
  - `tests.test_scalp_bot_e3`
  - `tests.test_scalp_bot_e3_portfolio`
  - 합계 `56 passed`

## §19 e3 범위확장 구현 (2026-08-20)

- `scripts/scalp_bot_e3.py`
  - 기존 `recenter_cycle()` 전량정리 경로는 유지.
  - 새 `expand_range_cycle()` 추가.
  - 범위 이탈 시 기본 동작을 `recenter` 가 아니라 `expand` 로 변경.
  - 새 CLI:
    - `--breakout-mode expand|recenter` (기본 `expand`)
    - `--range-expand-mult 1.5`

- `expand_range_cycle()` 동작:
  - 기존 대기 주문만 취소
  - **포지션은 청산하지 않음**
  - 중심가(`center_price`)는 유지
  - 폭(`width_pct`)만 단계적으로 넓혀 현재가가 새 범위 안에 들어오게 함
  - 기존 `held_buy_rungs`, `qty_per_rung`, `wallet_balance_start`, `realized_grid_profit_est` 유지
  - 새 주문은 빈 state 로 다시 깔리며 `RANGE_EXPAND` 이벤트 기록

- 의도:
  - 전량정리 없이 “넓어진 범위에서 계속 일하게” 만드는 것
  - 핸드오프 §18의 중간방식 검증에서 채택 권고된 **범위확장**을 코드 경로로 반영

- 현재 한계:
  - 재고 rung 는 기존 인덱스를 유지한다.
  - 즉, 확장 후 각 보유 칸의 “정확한 원래 매수가”를 새 격자에 다시 매핑하지는 않는다.
  - 하지만 전량 손절/강제정리 없이 실현손실 0 경로를 유지하는 것이 우선 목표라서,
    현재 단계에서는 이 단순 경로를 채택.

- 테스트:
  - `tests/test_scalp_bot_e3.py`
    - `test_expand_range_cycle_widens_range_without_flatten`
  - 현재 직접 재검증:
    - `tests.test_scalp_bot_e3`
    - `tests.test_scalp_bot_e3_portfolio`
    - 합계 `57 passed`

---

# 17. 재센터링 백테스트 — 앞선 +15% 는 비용이 빠진 값이었습니다

`scratchpad/grid_recenter.py` / 85심볼 10일 / **자본 100% 운용 / 3슬롯**

## 바뀐 운용 조건

| | §1~12 측정 | 이번 |
|---|---|---|
| 자본 사용률 | 0.65 | **1.00** |
| 슬롯 | 1심볼 전액 | **3슬롯** |
| 심볼당 자본 | 28.00 | **9.33** |
| 격자수 | 16 | 5 (자본에서 역산) |

## 재센터링 모델

범위를 벗어나면 (1) 재고 전량 **시장가** 정리 (2) 미체결 격자 취소
(3) 현재가 중심으로 재구성 (4) **현재 자기자본으로 칸당 수량 재계산**.
(4)에서 복리가 반영됩니다.

수수료를 구분했습니다 — 격자 체결은 지정가 **메이커 0.02%**,
재센터링 정리는 시장가 **테이커 0.05%**.

## 결과 — 재센터링을 넣으면 수익이 사라집니다

| 설정 | 청산률 | 수익 중앙 | 25% | 재센터 | 최대낙폭 | 이탈% |
|---|---|---|---|---|---|---|
| **재센터링 없음 ±10%** | 10.6% | **+17.70%** | -27.8 | 0 | 37.6% | 37.9% |
| 재센터링 없음 ±6% | 12.9% | +18.31% | -26.4 | 0 | 37.8% | 56.4% |
| 즉시 ±10% | **0.0%** | **-5.24%** | -35.3 | 11 | 41.3% | 0.1% |
| 즉시 ±6% | 0.0% | **-22.29%** | -60.6 | 33 | 48.6% | 0.2% |
| 5분 지속 ±10% | 1.2% | -14.54% | -35.0 | 9 | 46.0% | 0.6% |
| 30분 지속 ±10% | 4.7% | -11.81% | -47.7 | 7 | 50.0% | 2.7% |

## 비용 분해 — 수수료가 아니라 실현손실이 문제입니다

±10% 기준, 중앙값 USDT

| 설정 | 격자 실현 | **재센터 손실** | 재센터 수수료 | 총 수수료 |
|---|---|---|---|---|
| 재센터링 없음 | +2.7137 | 0.0000 | 0.0000 | 0.0308 |
| 즉시 | +0.1193 | **-9.7145** | 0.0712 | 0.1902 |
| 5분 지속 | -0.9739 | **-9.1680** | 0.0632 | 0.1672 |
| 30분 지속 | -0.0776 | **-8.0888** | 0.0462 | 0.1365 |

**재센터링 수수료는 0.05~0.07 로 무시할 수준입니다.**
진짜 비용은 **재고를 손실 상태로 정리하는 실현손실 -8~-9.7** 이고,
격자로 번 +2.7 의 세 배가 넘습니다.

### 왜 그런가

가격이 범위 아래로 벗어났다는 것은 **내려오는 내내 계속 사 모았다**는 뜻입니다.
그 시점의 재고는 전부 손실 상태입니다. 재센터링은 그걸 확정시킵니다.
새 범위에서 다시 사 모으다 또 벗어나면 또 확정합니다.
**하락 추세에서 손실을 반복 실현하는 기계**가 됩니다.

재센터링을 안 하면 손실이 미실현으로 남고 가격이 돌아오면 회복됩니다.
그래서 +17.70% 가 나옵니다 — 다만 **"돌아올 때까지 버틴다"** 는 전제이고,
대가가 청산률 10.6% 입니다.

## 3슬롯 포트폴리오

| 설정 | 중앙 | 최저 5% | 전액손실 |
|---|---|---|---|
| **재센터링 없음 ±10%** | **+6.53%** | -49.57% | 0.0% |
| 재센터링 없음 ±6% | +5.32% | -55.48% | 0.1% |
| 즉시 ±10% | -10.20% | -49.96% | 0.0% |
| 즉시 ±6% | -27.50% | -64.26% | 0.0% |
| 5분 지속 ±10% | -10.41% | -52.43% | 0.0% |
| 30분 지속 ±10% | -12.15% | -60.92% | 0.1% |

**자본 100% / 3슬롯 조건에서 유일하게 플러스인 것은 재센터링 없음(+6.53%)입니다.**

## 정리

1. **재센터링은 청산을 막지만 수익을 없앱니다.**
   즉시 ±10%: 청산률 10.6% → 0%, 수익 +17.70% → -5.24%
2. **±6% 는 어느 방식이든 나쁩니다.** 이탈이 잦아 재센터링이 33회 발생하고
   그때마다 손실을 확정합니다. **±10% 를 쓰십시오.**
3. **§1 의 +15%, §11 의 +17.70% 는 재센터링 비용이 빠진 값입니다.**
   실전에서 범위 재설정을 한다면 그 수치를 기대하면 안 됩니다.

## 다음에 재야 할 것 — 중간 방식

지금 모델은 **"전부 팔기"와 "아무것도 안 하기"** 두 극단만 비교했습니다.
그 사이가 비어 있습니다.

- **부분 정리** — 재고의 일부만 정리하고 나머지는 들고 간다
- **범위만 넓히기** — 재고는 유지하고 격자 범위만 확장한다(실현손실 0)
- **한쪽만 재배치** — 아래 격자는 두고 위쪽만 현재가 근처로 다시 깐다
- **손절선 병행** — 재센터링 대신 재고에 손절을 걸어 최악만 자른다

**이 중 하나라도 "청산률은 낮추면서 수익은 지키는" 지점이 있는지가 관건입니다.**
없다면 그리드는 "버티다가 가끔 죽는" 방식을 받아들이거나 포기해야 합니다.

---

# 18. 중간 방식 / 심볼 선별 / WS — 세 갈래 검증 (2026-08-21)

§17 의 "전부 팔기 vs 아무것도 안 하기" 두 극단 사이를 메우고,
심볼 선별과 WS 값어치를 함께 쟀습니다.

조건은 §17 과 동일합니다 — **자본 100% 운용 / 3슬롯 / 심볼당 9.33 USDT /
3배 / 격자 5개 / 폭 ±10%**.

스크립트: `scratchpad/grid_mid.py`, `grid_persist.py`, `grid_ws.py`

---

## [1] 중간 방식 — 범위확장이 최선입니다

| 방식 | 청산률 | 수익 중앙 | 25% 분위 | 최대낙폭 | 3슬롯 중앙 | 3슬롯 최저5% |
|---|---|---|---|---|---|---|
| 버티기 | 10.6% | +17.70% | -27.8 | 37.6% | +5.28% | -51.17% |
| **범위확장** | 11.8% | +12.13% | **-7.4** | **36.4%** | **+8.05%** | **-42.23%** |
| 전량정리 | **1.2%** | -14.54% | -35.0 | 46.0% | -11.48% | -52.44% |
| 절반정리 | 23.5% | -18.00% | -67.4 | 57.4% | -19.23% | -74.47% |
| 한쪽재배치 | 23.5% | -7.00% | -62.4 | 58.4% | -4.35% | -69.20% |

### 범위확장이란

이탈해도 **재고를 정리하지 않고** 격자 범위만 1.5배로 넓혀 다시 깝니다.
보유 칸은 새 격자의 가장 가까운 칸으로 옮깁니다. **실현손실이 0** 입니다.

### 왜 이기는가 — 비용 분해 (중앙값 USDT)

| 방식 | 격자 실현 | 재센터 손실 | 재센터 수수료 |
|---|---|---|---|
| 버티기 | +2.7137 | 0.0000 | 0.0000 |
| **범위확장** | **+4.0734** | **0.0000** | 0.0000 |
| 전량정리 | -0.9739 | -9.1680 | 0.0632 |
| 절반정리 | +1.2230 | -8.0909 | 0.0377 |
| 한쪽재배치 | +5.8848 | 0.0000 | 0.0000 |

**범위확장은 실현손실 0 을 유지하면서 격자 실현을 +2.71 → +4.07 로 늘립니다.**
범위가 넓어져 이탈 뒤에도 격자가 계속 일하기 때문입니다.
버티기는 이탈하면 격자가 멈춰 아무것도 못 합니다.

### 3슬롯 기준으로 버티기보다 낫습니다

- 중앙 **+8.05%** vs 버티기 +5.28%
- 최저 5% **-42.23%** vs 버티기 -51.17%
- **25% 분위 -7.4 vs 버티기 -27.8** — 나쁜 경우가 훨씬 얕다

### 기각 — 절반정리 / 한쪽재배치

둘 다 **청산률이 23.5% 로 뛰었습니다**(버티기 10.6%).
재고를 어중간하게 남긴 채 격자를 다시 까니 **손실은 확정하면서 위험은 그대로**
안고 갑니다. 한쪽재배치는 격자 실현이 +5.88 로 가장 큰데도 최종 성적이 나쁩니다 —
격자로 번 것보다 재고 손실이 더 커진다는 뜻입니다.

---

## [2] 심볼 선별 — 기준을 잘못 잡으면 정반대가 됩니다

10일을 전반 5일 / 후반 5일로 나눠 측정했습니다.

### 순위 상관은 약합니다

| 지표 | 전후반 순위상관 |
|---|---|
| 범위 이탈 비율 | +0.077 |
| **그리드 수익** | **-0.114** |
| 최대 낙폭 | +0.216 |
| 격자 체결수 | +0.228 |

**"전반에 잘 벌었던 심볼"은 후반에 오히려 못 법니다(-0.114).**
e1·e2 에서 수익 기준 심볼 선별이 기각됐던 것과 같은 방향입니다.

### 그런데 선별 효과는 큽니다

전반 성적으로 상위 K개를 고른 뒤 후반 성적입니다.

| 기준 | K | 선별 후반 | 무작위 후반 | 차이 |
|---|---|---|---|---|
| 이탈 적은 순 | 3 | +9.86% | -1.26% | +11.12 |
| **이탈 적은 순** | **5** | **+16.57%** | -0.90% | **+17.47** |
| 이탈 적은 순 | 10 | +18.78% | -0.87% | +19.65 |
| 낙폭 작은 순 | 3 | +14.00% | -1.79% | +15.79 |
| **낙폭 작은 순** | **5** | **+37.90%** | -1.07% | **+38.96** |
| 낙폭 작은 순 | 10 | +14.31% | -0.78% | +15.09 |
| **수익 높은 순** | 5 | **-47.09%** | -0.42% | **-46.67** |

**기준이 수익이 아니라 안정성이어야 합니다.**
이탈이 적거나 낙폭이 작은 심볼을 고르면 후반에도 잘 굴러가고,
**수익 높은 심볼을 고르면 정반대**가 됩니다(-46.67%p).

### 이 숫자를 그대로 믿으면 안 되는 이유

1. **상관(+0.077~+0.216)과 선별 효과(+17~39%p)가 어긋납니다.**
   이 불일치는 보통 꼬리 몇 개가 결과를 지배할 때 나타납니다.
   상위 5개를 고르는 것은 **표본 5개짜리 결정**입니다.
2. **단조롭지 않습니다.** 낙폭 기준이 K=3 +14.00 / K=5 +37.90 / K=10 +14.31 로
   K=5 만 튑니다. 안정적인 신호라면 K 에 따라 완만하게 변해야 합니다.
3. **전반/후반 한 번의 분할**입니다. 워크포워드가 아닙니다.
   이 5일 구간에서만 통했을 수 있습니다.

**현재 판정: 유망하지만 근거 부족.** 채택하려면 여러 시점으로 굴려가며(rolling)
재고 심볼 분할까지 넣어야 합니다.

---

## [3] WS — 이 자본에서는 값어치가 0 입니다

같은 1초 데이터로 두 모드를 비교했습니다.
WS 모드는 체결을 즉시 반영해 그 초에 반대편 격자를 걸고,
폴링 모드는 1분 경계까지 기다립니다.

| 모드 | 격자 체결 | 격자 실현 | 수수료 | 순익 |
|---|---|---|---|---|
| WS(1초) | 28 | +2.7098 | 0.0313 | +2.6785 |
| 폴링(1분) | 28 | +2.7098 | 0.0313 | +2.6785 |

**완전히 동일합니다. 차이 +0.0000 USDT.**

### 왜 0 인가

격자 간격이 원인입니다. 자본 9.33 × 3배 ÷ 최소주문 5 = **격자 5개**,
폭 ±10% 이므로 **간격이 4%** 입니다.
1분 안에 가격이 4% 격자를 두 번 넘나드는 일이 거의 없으므로
폴링이 놓치는 기회가 없습니다.

**WS 는 격자가 촘촘할 때만 의미가 있고, 그러려면 자본이 커야 합니다.**
지금 자본에서는 붙일 이유가 없습니다.
e2 의 WS 레이어를 그리드로 옮기는 작업은 **보류하십시오.**

---

## 종합

| 검증 | 결론 | 채택 여부 |
|---|---|---|
| [1] 중간 방식 | **범위확장** — 3슬롯 +8.05%, 최저5% -42.23% | **채택 권고** |
| [2] 심볼 선별 | 안정성 기준 유망, 수익 기준 역효과 | **보류** (검증 부족) |
| [3] WS | 값어치 0 (격자 간격 4%) | **기각** |

## 다음에 할 것

1. **범위확장을 e3 에 구현** — 지금 `recenter_cycle` 은 전량정리 방식이다.
   재고를 유지하고 범위만 넓히는 경로를 추가해야 한다.
2. **심볼 선별 재검증** — 굴림 분할(rolling)로 여러 시점에서 재고,
   심볼 분할까지 넣을 것. 통과하면 "이탈 적은 순" 또는 "낙폭 작은 순"으로
   상위 3~5개를 고르는 규칙을 넣는다.
3. **WS 는 하지 말 것** — 자본이 100 USDT 를 넘어 격자가 촘촘해지면 다시 잰다.

---

# 19. V2(체결 흐름) 활용 검증 — 기각 (2026-08-21)

"V2 가 있으니 유리한 방향으로 격자를 설정할 수 있지 않나" 를 측정했습니다.

**V2 = aggTrades 의 `isBuyerMaker` 로 갈라낸 테이커 매수/매도 흐름.**
`scratchpad/sec30/` 7번째 필드가 같은 값이라 백테스트가 가능했습니다.
(`fetch_sec.py` 30행 `bm=p[6]=='true'`, 39행 `if not bm: b[5]+=q`)

```
매수압력 = 테이커매수량 / 전체거래량      (0.5 = 균형)
```

스크립트: `scratchpad/grid_v2.py`, `grid_shift.py`
조건: 범위확장 / 자본 100% / 3슬롯 / 심볼당 9.33 / 3배 / 폭 ±10% / 85심볼

## A. 필터 — 단조롭지 않아 규칙이 안 됩니다

| 매수비율 | 심볼 | 수익 중앙 | 청산률 |
|---|---|---|---|
| <0.45 | 18 | **+21.89%** | 5.6% |
| 0.45~0.48 | 12 | +7.06% | 8.3% |
| 0.48~0.52 | 17 | +11.12% | 17.6% |
| 0.52~0.55 | 24 | **+0.86%** | 20.8% |
| 0.55~ | 14 | +15.09% | 7.1% |

**양 끝이 좋고 가운데가 나쁜 U자**입니다. 방향과 무관하게 "쏠려 있을 때" 좋다는
뜻인데, 구간당 표본이 12~24개뿐이라 규칙으로 쓸 수 없습니다.

## B. 지속성 — 압력은 이어지지만 수익으로 연결되지 않습니다

| | 순위상관 |
|---|---|
| **전반 압력 vs 후반 압력** | **+0.518** |
| 시작 전 압력 vs 그리드 수익 | **-0.117** |
| 시작 전 압력 vs 이탈 비율 | -0.038 |

**압력의 지속성 +0.518 은 이 프로젝트에서 본 것 중 가장 강한 값입니다.**
심볼의 성격이 실재한다는 뜻입니다. 그런데 **그것이 수익을 예측하지 못합니다.**
오히려 약한 음의 상관(-0.117)입니다.

**"성격이 이어진다"와 "돈이 된다"는 다른 이야기**라는 것을 다시 확인했습니다.

## C. 비대칭 배치 — V2 가 아니라 '중심 이동' 효과였습니다

처음에는 압력 방향으로 중심을 옮기면 매수우위 그룹에서 **+9.07%p** 개선으로
보였습니다. 압력과 무관하게 전 심볼에 같은 이동을 적용해 갈라냈습니다.

| 이동 | 수익 중앙 | 25% 분위 | 청산률 | 격자 체결 |
|---|---|---|---|---|
| -4% | +10.78% | -10.18 | 12.9% | 19 |
| -2% | +13.11% | -8.50 | 11.8% | 23 |
| 고정 | +12.32% | -5.06 | 12.9% | 22 |
| +2% | +14.25% | -4.16 | 14.1% | 23 |
| **+4%** | **+15.26%** | -6.69 | 12.9% | 21 |

**압력과 무관하게 위로 옮길수록 좋아집니다.** V2 신호 덕이 아니었습니다.

그룹별로 보면 최적 이동이 제각각입니다.

| 그룹 | 심볼 | -4% | -2% | 고정 | +2% | +4% | 최적 |
|---|---|---|---|---|---|---|---|
| 매수우위 p>0.52 | 38 | +8.87 | +8.09 | +5.74 | +14.81 | +14.84 | +4% |
| 중립 0.48~0.52 | 17 | +13.99 | +10.70 | +11.12 | +4.20 | +10.52 | **-4%** |
| 매도우위 p<0.48 | 30 | +15.18 | +15.27 | +18.37 | +18.41 | +17.43 | +2% |

**압력이 최적 이동을 예측한다면 순서가 있어야 하는데 없습니다.**
매도우위 그룹은 이동 폭에 거의 반응하지 않고(+15.18~+18.41),
매수우위 그룹만 크게 흔들립니다(+5.74~+14.84). 규칙이 아니라 우연에 가깝습니다.

### 다만 '중심 위로'는 약한 후보로 남습니다

중심을 위로 올리면 현재가가 범위 아래쪽에 놓여 **아래쪽 매수 격자가 줄어듭니다.**
롱 그리드는 내려갈수록 재고를 쌓으므로, 아래쪽 격자가 적으면 물리는 양이 줍니다.
청산률은 거의 그대로인데(12.9%→12.9%) 수익이 +12.32 → +15.26 으로 개선된 것이
그 방향과 맞습니다. **다만 그룹 일관성이 없어 확정하지 마십시오.**

## 결론

| 용도 | 판정 |
|---|---|
| 그리드 진입 필터 | **기각** (수익 상관 -0.117, U자 분포) |
| 비대칭 배치 신호 | **기각** (중심 이동 효과였음) |
| 심볼 선별 | **기각** (지속성은 있으나 수익 무관) |

**V2 는 그리드에 쓸모가 없습니다.** e1 에서 테이커 게이트가 기각됐고
§13 에서 거래량이 실릴수록 나빴던 것과 같은 방향입니다.

## 조치 — 코드·데이터는 보존, 실행만 중지

사용자 요청("데이터는 남겨놓고 실행만 하지 않게")에 따라 `.env` 만 바꿨습니다.

```
WS_TRADE_USE_V2=true  ->  false
```

- 백업: `.env.bak_v2off`
- `TradeStreamWebSocketV2` 클래스, 수집 데이터, 나머지 설정은 **그대로**
- 되살리려면 이 값만 `true` 로 바꾸면 됩니다
- 참고: `SPIKE_ENTRY_ENABLED=true` 는 건드리지 않았습니다.
  V2 가 꺼지면 V0 스트림으로 동작합니다. 이것도 끄려면 별도 판단이 필요합니다

---

# 20. 라이브 관측 — e3_portfolio 회전 손실 (2026-08-21 02:05~02:12)

**코덱스 확인 요청.** 클로드는 `scalp_bot_e3_portfolio.py` 를 수정하지 않았습니다
(02:10:46 에 코덱스가 편집 중인 것으로 보여 관측만 기록합니다).

## 증상 — 2분 주기로 사고팔며 손실을 누적

최근 30분 거래소 원본:

| 항목 | 값 |
|---|---|
| REALIZED_PNL | **-0.1453** (9건) |
| COMMISSION | -0.0462 (16건) |
| **합계** | **-0.1915** |

30분에 -0.19 이면 하루 -9 USDT 속도입니다. 자산(28)의 약 1/3 입니다.

원장 이벤트(같은 구간):

```
PLACE_BUY 32 / BUY_FILLED 7 / PLACE_SELL 7 / PLACE_ORDER_FAILED 7
```

**PLACE_BUY 32건 중 체결 7건, 실패 7건**입니다.

## 체결 패턴 — 매수 후 2분 내 전량 정리가 반복됩니다

```
ACEUSDT  02:05:37 BUY  31.51 @0.257530
         02:07:42 SELL 31.51 @0.254720   realized -0.0885
         02:08:51 BUY  54.70 @0.255500
         02:09:34 SELL 54.70 @0.256790   realized +0.0706

ONGUSDT  02:07:42 SELL 112 @0.08048      realized -0.1053
         02:07:42 SELL  21 @0.08048      realized -0.0197
         02:08:47 BUY  175 @0.07970
         02:09:34 SELL 175 @0.07963      realized -0.0123
```

02:07:42 와 02:09:34 에 **두 심볼이 동시에 전량 정리**됐습니다.
슬롯 전환이나 재센터링이 그 시각에 함께 발동한 것으로 보입니다.

**§17 에서 측정한 그대로입니다** — 재센터링(전량정리)은 청산을 막지만
재고를 손실 상태로 확정시켜 수익을 없앱니다. 백테스트 기준
전량정리 -14.54% vs 버티기 +17.70% 였고, 대안으로 **범위확장**(재고 유지,
범위만 넓힘, 실현손실 0)이 3슬롯 +8.05% 로 최선이었습니다.

## 상태-거래소 불일치 (재현됨)

봇의 상태파일은 슬롯마다 매수·매도 주문이 1건씩 살아 있다고 봅니다.

```
slot 1 ACEUSDT 보유1 매수1 매도1
slot 2 ONGUSDT 보유1 매수1 매도1
```

거래소 조회 결과는 **전부 CANCELED, 포지션 0, 미체결 0** 입니다.

```
ACEUSDT buy rung0  id=5463938446 -> CANCELED executedQty=0.00
ACEUSDT sell rung2 id=5463970909 -> CANCELED executedQty=0.00
ONGUSDT buy rung0  id=2838332602 -> CANCELED executedQty=0
ONGUSDT sell rung2 id=2838341180 -> CANCELED executedQty=0
```

**§14 에서 테스트로 고정해 둔 한계가 실제로 발생했습니다.**
(`test_resume_does_not_reconcile_orders_with_exchange`)
`load_state` 는 저장된 주문을 그대로 믿고 거래소를 조회하지 않습니다.

## 확인이 필요한 것

1. **02:07:42 / 02:09:34 의 동시 전량 정리가 무엇인가** — 슬롯 전환인지
   재센터링인지. `--min-switch-interval-sec 1200` 인데 2분 만에 정리됐다면
   전환이 아니라 재센터링일 가능성이 높습니다
2. **PLACE_ORDER_FAILED 7건의 사유** — `-2022`? `-1111`(정밀도)? 레이트리밋?
   §16 에서 지적했듯 `place_limit_order` 에 예외 처리가 없어 한 칸 거부가
   루프를 중단시킵니다
3. **재센터링 방식** — 지금 전량정리라면 **범위확장으로 바꾸는 것을 권합니다**(§18)
4. **상태-거래소 대조** — 재개 시 미체결 주문을 조회해 상태와 맞추는 경로 필요

## 재시작 이력 (참고)

- 02:04 이전: 구버전 프로세스, 포지션 1건 / 미체결 5건 보유
- 02:05: 클로드가 `--resume` 붙여 재시작 (차트·브리핑 반영 목적)
- 02:05~02:12: 위 회전 발생
- 02:10:46: 코덱스가 `scalp_bot_e3_portfolio.py` 수정

**재시작 자체가 원인일 가능성도 배제하지 못합니다.** `--resume` 으로 올렸지만
상태파일의 주문이 이미 취소된 상태였으므로, 봇이 잘못된 전제로 시작했을 수 있습니다.

---

# 21. Codex 조치 — stale 정리, resume 대조, 15분 무체결 교체 (기록 시각: 2026-08-21 새벽 로그 기준)

이번 섹션은 **실제 코드 반영 + 테스트 통과 + 재기동 확인**까지 끝난 항목만 적습니다.

## 1. 들어간 코드 변경

### A. 재개 시 상태-거래소 대조

`scripts/scalp_bot_e3_portfolio.py`

- `reconcile_portfolio_with_exchange()` 추가
- 상태파일에 슬롯이 남아 있어도, 거래소에 **해당 심볼의 미체결 주문/포지션이 둘 다 없으면**
  그 슬롯을 stale 로 보고 비웁니다
- 원장 이벤트:

```
PORTFOLIO_RESUME_CLEAR
```

이것으로 §20 에서 실제로 터졌던
“상태파일은 살아 있는데 거래소는 비어 있는” 문제를 재시작 시 바로 털어냅니다.

### B. 15분 무체결 자동 교체

단일 E3와 포트폴리오 E3에 `last_fill_at` 을 추가했습니다.

`scripts/scalp_bot_e3.py`
- `CycleState.last_fill_at`
- `BUY_FILLED`, `SELL_FILLED` 때 갱신

`scripts/scalp_bot_e3_portfolio.py`
- 새 옵션:

```
--idle-switch-sec 900
```

- 현재 슬롯이 아래 조건을 모두 만족하면 다른 심볼로 교체합니다.

1. **보유 칸이 0**
2. **매수 대기만 있고 매도 대기는 없음**
3. **마지막 체결 또는 시작 시점 이후 900초(15분) 이상 경과**
4. **상위 후보가 현재 슬롯보다 점수가 충분히 높음**

즉, 아직 보유가 생긴 슬롯을 억지로 흔들지 않고,
**“아예 체결이 안 되어 자본이 놀고 있는 슬롯”만** 교체합니다.

준비 이벤트:

```
PORTFOLIO_IDLE_SWITCH_READY
```

실제 스위치 이벤트:

```
PORTFOLIO_SWITCH reason="idle"
```

### C. 기존 범위확장 경로 유지

무체결 교체를 넣었어도, **범위 이탈 시 1순위는 여전히 범위확장**입니다.
즉 “가격이 움직여 범위를 벗어난 경우”와
“가격이 너무 안 움직여 체결이 안 되는 경우”를 분리했습니다.

---

## 2. 테스트 결과

Codex 실행 결과:

| 묶음 | 결과 |
|---|---|
| `tests.test_scalp_bot_e3_portfolio` + `tests.test_scalp_bot_e3` | **71 passed** |

이번에 특히 추가/고정된 검증:

- `reconcile_portfolio_with_exchange` 가 stale 슬롯을 비우는지
- live fill 시 `last_fill_at` 이 갱신되는지
- **15분 무체결 슬롯이 실제로 새 심볼로 교체되는지**

---

## 3. 재기동 직전 확인

Codex 가 재기동 직전에 거래소를 조회한 결과:

| 항목 | 값 |
|---|---|
| open orders | 0 |
| open positions | 0 |

사용자가 “보유하고 있던 거래는 내가 올 취소했어”라고 말했고,
조회 결과도 그와 일치했습니다.

즉 이번 재기동은 **dirty resume 가 아니라 clean start** 였습니다.

---

## 4. 재기동 결과

기존 프로세스:

```
STOPPED 16596
```

새 프로세스:

```
PID 13372
```

기동 인자:

```powershell
scripts/scalp_bot_e3_portfolio.py
  --slots 3
  --strategy-mode fast
  --leverage 3
  --capital-usage 1.0
  --candidate-limit 60
  --top-candidates 12
  --score-eval-sec 300
  --min-switch-interval-sec 1200
  --switch-score-delta 15
  --idle-switch-sec 900
  --max-loss-pct 7
  --exclude-symbols XRPUSDT
  --i-understand-grid-risks
```

재기동 직후 거래소 실주문:

| 항목 | 값 |
|---|---|
| open orders | **6** |
| open positions | 0 |
| 배정 심볼 | `ACEUSDT`, `ONGUSDT`, `BOMEUSDT` |

실제 올라간 주문은 각 슬롯당 **매수 2개씩**, 총 6개입니다.

즉 “프로세스만 떴다”가 아니라 **거래소에 주문까지 올라간 상태**입니다.

---

## 5. 지금 클로드가 알면 좋은 운영 해석

1. **지금은 표본이 아직 없습니다.**
   재기동 후 원장 최신 구간은 `PLACE_BUY 6건`뿐이라
   승률/시간당 거래수/보유시간을 라이브 확정치로 말하면 안 됩니다.

2. **무체결 교체는 ‘빠른 순환’ 목적의 보강 규칙이지, 그리드 원칙 위반이 아닙니다.**
   범위 안에서 왕복할 가능성이 낮은 심볼을 오래 붙잡지 않겠다는 뜻입니다.

3. **다만 15분도 공격적인 편입니다.**
   다음 관찰 포인트는
   “실제로 15분 후 idle switch 가 너무 자주 발생하는가”
   “체결 직전 코인을 너무 빨리 버리지는 않는가” 입니다.

4. **다음 실관찰 체크포인트**
   - `PORTFOLIO_IDLE_SWITCH_READY` 가 실제로 뜨는지
   - 그 직후 `PORTFOLIO_SWITCH reason="idle"` 로 이어지는지
   - idle switch 후 1시간 체결 수가 늘었는지
   - 반대로 취소만 늘고 체결이 늘지 않는지

---

## 6. 관련 파일

- `scripts/scalp_bot_e3.py`
- `scripts/scalp_bot_e3_portfolio.py`
- `tests/test_scalp_bot_e3.py`
- `tests/test_scalp_bot_e3_portfolio.py`

---

# 22. 회전 속도 · 이익순환 · 교체주기 검증 (2026-08-21)

"그리드를 빠르게 순환시켜 자산을 증식한다"가 가능한지 네 갈래로 쟀습니다.
공통 조건: 자본 9.33 USDT(28/3슬롯) / 3배 / 자본 100% / 격자 5개 / 85심볼 10일.

스크립트: `scratchpad/grid_cycle.py`, `grid_turnover.py`, `grid_idle.py`, `grid_move.py`

---

## 22-1. 격자 회전 시간 — 중앙 270분(4.5시간)

| 구간 | 값 |
|---|---|
| 25% | 65분 |
| **중앙** | **270분 (4.5시간)** |
| 75% | 1,212분 (20.2시간) |
| 90% | 3,709분 (61.8시간) |
| 평균 | 1,166분 |

| 분포 | 비중 |
|---|---|
| 15분 이내 | 9.8% |
| 15~60분 | 13.7% |
| 1~4시간 | 23.2% |
| **4~24시간** | **30.8%** |
| 1일 초과 | 22.4% |

- 첫 매수까지 중앙 **97분**
- 재고 0인 시간 비중 중앙 **1.2%** (일단 재고가 생기면 거의 계속 보유)

**간격 4%가 원인입니다.** 자본 9.33 × 3배 ÷ 최소주문 5 = 격자 5개가 상한이고,
폭 ±10% 면 간격이 4% 입니다. 4% 내려가 사고 4% 올라와야 팝니다.

---

## 22-2. 이익 순환 — 기각

"N분마다 이익이면 전량 정리하고 다시 깐다"를 쟀습니다.

| 설정 | 청산률 | 수익 중앙 | 25% | 순환 | **익절합** | 3슬롯 중앙 |
|---|---|---|---|---|---|---|
| **버티기(범위확장)** | 11.8% | **+15.22%** | **-6.52** | 0 | 0.0000 | **+8.21%** |
| 30분 순환 문턱1.0% | 16.5% | +2.16% | -23.14 | 343 | **-2.3078** | -10.47% |
| 60분 순환 문턱1.0% | 15.3% | +1.79% | -29.48 | 180 | -3.1118 | -10.18% |
| 15분 순환 문턱0.0% | 21.2% | +0.46% | -40.83 | 770 | -1.2330 | -30.78% |

**익절합이 전부 마이너스입니다.** "이익일 때만 정리"인데도 그렇습니다.

**이유**: 판정은 **자기자본**(실현+미실현)으로 하는데 정리 대상은 **재고**입니다.
격자가 여러 번 맞물려 실현이익이 쌓여 있으면 재고가 손실이어도 자기자본은 플러스입니다.
그때 "이익이다"라고 판단해 정리하면 **손실 재고를 확정**합니다.
§17 의 재센터링과 같은 함정에 다른 경로로 빠집니다.

주기가 짧을수록 나쁘고(15분 -30.78% < 30분 -10.47% < 60분 -10.18%),
문턱을 0%→1% 로 올려도 거의 바뀌지 않습니다.

---

## 22-3. 확장 배수 · 범위이동 — 회전을 올리면 반드시 재고가 쌓입니다

| 설정 | 회전중앙 | 거래수 | 수익중앙 | 25% | 청산률 | 재설정 | 낙폭 |
|---|---|---|---|---|---|---|---|
| **확장1.5 ±10%** | 276분 | 20 | **+15.22%** | -6.98 | **11.8%** | 4 | **31.4%** |
| 확장1.2 ±10% | 268분 | 24 | +11.95% | -12.82 | 14.1% | 8 | 37.5% |
| 확장1.1 ±10% | 237분 | 26 | +8.50% | -15.62 | 12.9% | 13 | 39.8% |
| 이동 ±10% | **47분** | 76 | -11.82% | -100.00 | 34.1% | 9 | 71.8% |
| 이동 ±5% | **13분** | 188 | -100.00% | -100.00 | 63.5% | 22 | 97.9% |
| 이동 ±2% | 4분 | 505 | -100.00% | -100.00 | 82.4% | 53 | 97.7% |
| 이동 ±1% | **2분** | 677 | -100.00% | -100.00 | **90.6%** | 73 | 96.4% |

3슬롯 포트폴리오: 확장1.5 **+8.28%** / 확장1.2 +4.14% / 확장1.1 +4.40% /
이동±10% -6.26% / 이동±5% -40.23% / 이동±2%·±1% -100%

### 회전은 원하는 대로 빨라집니다 — 그리고 전멸합니다

| 설정 | 15분내 | 1~4h | 4~24h |
|---|---|---|---|
| 확장1.5 | 9.9% | 23.2% | 30.5% |
| 이동 ±10% | 30.2% | 21.1% | 17.9% |
| 이동 ±1% | **85.7%** | 3.0% | 0.6% |

**이동 ±1% 는 85심볼 중 90.6% 가 청산됐습니다.**

**구조적 이유**: 범위를 현재가로 계속 옮기면 가격이 내려갈 때마다 격자를
그 아래에 다시 깝니다. 내려가는 내내 계속 사 모으고, 폭이 좁을수록 더 자주
더 많이 삽니다. 재고가 눈덩이처럼 불어나 3배에서 청산됩니다.

**확장 방식은 반대로 브레이크가 걸립니다.** 범위가 넓어지면 간격도 벌어져
추가 매수 속도가 저절로 느려집니다. 배수를 1.5→1.1 로 낮추면 그 브레이크가
약해져 재설정이 4회→13회로 늘고 낙폭이 31.4%→39.8% 로 커집니다.

### 결론

**"빠른 순환으로 증식"은 이 구조에서 성립하지 않습니다.**
회전을 빠르게 만드는 모든 방법이 재고 축적 속도를 함께 올립니다.
지금까지 잰 것 중 **가장 느린 확장1.5 ±10% 가 가장 높은 수익**입니다.

회전을 올리면서 재고를 안 쌓는 유일한 길은 **격자를 촘촘히 까는 것**이고,
그것은 자본이 커져야 가능합니다(격자 20개 = 자본 약 34 USDT at 3배).

---

## 22-4. 무체결 교체 주기 — 30분이 최적

첫 체결까지: 25% 14분 / **중앙 97분** / 75% 253분 / 90% 451분
(체결이 아예 없던 심볼 0개)

| 문턱 | 조기교체율 | 버리는 수익 | 남는 수익 | 새 심볼 기대 | **순효과** |
|---|---|---|---|---|---|
| 15분 | 70.6% | +4.1806 | +5.1394 | +4.4579 | +0.2774 |
| **30분** | 68.2% | +4.1032 | +5.2346 | +4.4533 | **+0.3501** |
| 60분 | 57.6% | +4.2142 | +4.8006 | +4.4440 | +0.2297 |
| 90분 | 51.8% | +4.1866 | +4.7588 | +4.4347 | +0.2481 |
| 120분 | 43.5% | +4.2159 | +4.6527 | +4.4254 | +0.2095 |
| 240분 | 27.1% | +4.4324 | +4.4738 | +4.3882 | **-0.0442** |

**"버리는 수익"이 문턱과 무관하게 +4.1~4.4 로 평평합니다.**
첫 체결이 늦은 심볼이라고 결국 덜 벌지 않습니다. 그래서 오래 기다릴 이유가 없고,
빨리 갈아탈수록 남은 시간이 길어 유리합니다. 단 240분에서는 뒤집힙니다.

**클로드의 앞선 권고 정정**: "첫 체결 중앙 97분이니 15분은 이르다 → 90~120분으로"
는 **틀렸습니다.** 늦게 시작하는 심볼을 버려도 손해가 아니라는 것을 재보고 알았습니다.

**주의**: 문턱 간 차이가 +0.07 수준이고 순서도 단조롭지 않습니다(60분 < 90분).
교체 비용(주문 취소·재배치, 라이브에서 `PLACE_ORDER_FAILED` 7건)이
모델에 없습니다. **"30분이 최적"은 맞고 "얼마나 나은지"는 불확실합니다.**

---

## 22-5. 적용 상태

**범위확장 1.5배는 이미 라이브 기본값입니다.** 새로 바꿀 것이 없습니다.

- `scalp_bot_e3.py:816` `expand_range_cycle(width_mult=1.5)`
- `scalp_bot_e3.py:872` `--breakout-mode` 기본 `expand`
- `scalp_bot_e3_portfolio.py:506` 도 `expand_range_cycle` 호출

**포트폴리오 봇에는 `--range-expand-mult` / `--breakout-mode` 인자가 없습니다.**
1.5배 확장이 코드에 고정돼 있습니다.

변경할 것은 하나입니다.

```
--idle-switch-sec 900  ->  1800
```

두 설정은 다른 상황을 다루므로 함께 적용됩니다.

| 설정 | 언제 작동 |
|---|---|
| 범위확장 1.5배 | 가격이 **움직여** 범위를 벗어났을 때 |
| 무체결 교체 30분 | 가격이 **안 움직여** 체결이 없을 때 |

## 22-6. 재시작 실패 — 선물 지갑 잔고 0

`--idle-switch-sec 1800` 으로 재시작했으나 **"총 자산이 0 이하입니다"** 로 종료됐습니다.

```
02:59:56  TRANSFER -28.10471681 USDT   (선물 -> 외부)
```

현재 선물 지갑 잔고 0, 포지션 0, 미체결 0 입니다.
**자금이 선물 지갑으로 돌아와야 재시작할 수 있습니다.**

---

# 23. 야간 자율 점검 (2026-08-21 03:00~) — 클로드

사용자가 취침하며 5개 항목에 대한 수정·재시작 권한을 부여함.
"자산 증식을 빠르게"가 1순위.

## 0) 불필요한 대기 주문 자동 정리 — 조치 불필요

현재 미체결 5건 전수 확인 결과 **슬롯 밖 심볼 주문 0건, 상태파일 미등록 주문 0건**.
코덱스가 §21 에 넣은 `reconcile_portfolio_with_exchange()` / `PORTFOLIO_RESUME_CLEAR`
가 이미 작동 중이라 추가 로직이 필요 없음.

## 1) 체결이 느린 근본 원인 — 격자 칸수

실측: 슬롯 2개 모두 **격자 3칸, 간격 4.26%, 칸당 명목 10.09 USDT**.
프로파일 `speed_6x4`(폭 ±6%, 4칸)가 `fast` 모드에서 가장 촘촘한 선택지였음.

**칸당 명목에 여유가 있었다.** 최소주문 5.0 USDT 대비 10.09 로 2배.

```
슬롯당 명목 = 29.28 / 2슬롯 x 3배 = 43.9 USDT
  4칸 -> 칸당 10.98   (현재)
  6칸 -> 칸당  7.32   OK
  7칸 -> 칸당  6.27   OK
  9칸 -> 칸당  4.88   최소 미달
```

### 조치 — 촘촘한 프로파일 4종 추가

`build_strategy_profiles("fast")` 에 추가:

| id | 폭 | 격자 | 간격 |
|---|---|---|---|
| rapid_5x6 | 5.0% | 6 | **2.00%** |
| rapid_6x7 | 6.0% | 7 | **2.00%** |
| quick_6x6 | 6.0% | 6 | 2.40% |
| quick_8x7 | 8.0% | 7 | 2.67% |

**`filter_profiles_for_wallet()` 도 함께 고쳤다.** 잔고 250 미만에서
`{speed_6x4, fast_8x4}` 만 허용하고 있어서, 새 프로파일이 전부 걸러지고 있었다.
소액 지갑 허용 목록에 4종을 추가했다.

**왜 이 방향이 안전한가**: 격자를 늘려도 **총 명목은 그대로**다(자본 x 레버리지).
자본을 잘게 나눌 뿐이라 내려갈 때 사 모으는 총량이 같다.
§22-3 에서 기각한 '범위 이동'(청산률 90.6%)이나 '폭 축소'와는 성격이 다르다.

**적용 시점**: `--resume` 으로 기존 슬롯을 이어받아 아직 옛 프로파일(6x4)이 남아 있다.
다음 슬롯 교체 때 새 프로파일이 선택된다. 강제 적용하려면 포지션 정리가 필요해
비용이 크므로 자연 교체를 기다리는 쪽을 택했다.

## 2) 그리드 + 순환 매매 성격 재검토

§22 까지의 측정을 종합하면 **"빠른 순환으로 증식"은 이 구조에서 성립하지 않는다.**

| 시도 | 회전 | 결과 |
|---|---|---|
| 범위 이동 ±1% | 2분 | **청산률 90.6%** |
| 범위 이동 ±5% | 13분 | 청산률 63.5%, -100% |
| 확장 배수 1.1 | 237분 | 수익 반토막(+15.22 -> +8.50) |
| 이익 순환 30분 | — | 익절합 -2.31, 3슬롯 -10.47% |
| **버티기 + 범위확장 1.5** | 276분 | **3슬롯 +8.28%** (최선) |

**회전을 빠르게 만드는 모든 방법이 재고 축적 속도를 함께 올린다.**
유일한 예외가 **격자 칸수를 늘리는 것**이다 — 총 명목이 불변이므로.
그래서 1) 의 조치가 "빠르게"에 대한 유일한 정당한 답이다.

**근본 제약은 자본이다.** 자본 29 USDT / 2슬롯 / 3배면 슬롯당 명목 43.9,
최소주문 5 로 나누면 격자 8칸이 상한이다. 자본이 커져야 더 촘촘해진다.

## 3) 버그 확인

### PLACE_ORDER_FAILED 7건 — 전부 `-2019 Margin is insufficient`

발생 시각이 **01:52:45~01:53:11 에 집중**, 최근 60분 0건.
당시 `LEGACY_ADOPT` 13건으로 레거시 포지션이 증거금을 함께 쓰고 있었다.
현재는 정리돼 재발하지 않는다.

**`--capital-usage 1.0` 은 그대로 둔다.** 격자 전량 체결 시에도
증거금 사용률이 69% 로 31% 여유가 남는다(레버리지 3배라 명목/3 만 증거금).

```
격자 전량 체결 시 총 명목 60.58 -> 필요 증거금 20.19 / 지갑 29.25 (69%)
현재 가용 11.86 (여유율 40.5%)
```

### 매도 주문이 없어 보이던 건 — 오탐

03:14 조회에서 매도가 0건이라 격자가 반쪽만 돈다고 의심했으나,
03:15:28 에 `BUY_FILLED` 직후 `PLACE_SELL` 이 정상 기록됐다. 조회 시점이 체결 전이었다.

### 락 파일 고아 PID — 재시작 실패 원인

`logs/scalp_bot_e3_bot_pid.json` 에 죽은 PID 2880 이 남아
`[중단] 이미 e3 봇이 실행 중입니다` 로 기동이 거부됐다.
현재 `_pid_alive()` 는 tasklist 로 생존을 보는데, 죽은 PID 면 락을 가져가야 한다.
이번엔 수동으로 지웠다. **재발하면 `acquire_bot_lock` 의 stale 판정을 확인할 것.**

## 4) 정기 모니터링 — cron 등록

매시 **02분·32분**에 자동 점검(세션 한정, 7일 후 만료).

점검 항목: 프로세스 생존·중복 / 계좌-상태파일 대조 / 원장-거래소 실현손익 대조 /
완결 격자 복기(체류·승률·순익) / 슬롯 격자 간격 / 손실컷 근접 여부.

**중단 기준**: 30분에 -0.3 USDT 초과 손실이면 봇을 멈추고 원인 기록.

## 테스트

```
867 passed, 26 subtests passed
```

V2 테스트 2건은 주석 안내("끌 때는 이 단언을 반대로 갱신할 것")대로 갱신했다.
`.venv312` 에도 matplotlib 을 설치했다(차트 테스트 수집 실패 해소).

## 현재 상태 (03:2x)

- PID 2124 단일 인스턴스, 잔고 **29.21**, 기준 29.00
- slot1 TUTUSDT 보유1 / slot2 HEMIUSDT 보유0, 둘 다 옛 프로파일 6x4
- 미체결 5건 전부 정상, 고아 주문 없음

---

# 24. 실사고 — 두 슬롯이 같은 심볼을 잡아 손실컷 발동 (2026-08-21 03:4x)

**40분 만에 -2.91 USDT, 손실컷(7%) 발동으로 봇 정지.**

## 무슨 일이 있었나

```
03:46:17 BUY_FILLED BEATUSDT rung1
03:46:18 BUY_FILLED BEATUSDT rung1   <- 같은 칸을 두 번
03:47:23 BUY_FILLED BEATUSDT rung0
03:47:23 BUY_FILLED BEATUSDT rung0   <- 또 두 번
03:47:36 BUY_FILLED BEATUSDT rung0
03:47:37 BUY_FILLED BEATUSDT rung0   <- 네 번째
03:47:43 GLOBAL_STOP  29.1578 -> 26.7119 (-8.4%, 문턱 7%)
```

거래소 원본(40분): REALIZED_PNL **-2.8643** / COMMISSION -0.0716
심볼별: **BEATUSDT -2.9115** / TUTUSDT -0.0244

상태파일 확인 시 **slot1·slot2 가 둘 다 BEATUSDT** 였습니다.

## 원인 — 슬롯 간 심볼 중복 방지가 없었다

`maybe_rotate_slot()` 은 **슬롯마다 따로 호출**되는데, 같은 `candidate_snapshot`
을 보면서 **다른 슬롯이 이미 쓰는 심볼을 후보에서 빼지 않았습니다.**
그래서 두 슬롯이 동시에 최고점수 심볼(BEATUSDT)로 교체됐습니다.

`pick_symbols()` 에 중복 제거가 있지만 **한 번의 선택 안에서만** 작동합니다.
슬롯이 다른 시점에 교체되면 무력합니다.

### 두 가지 피해가 겹칩니다

1. **재고 2배** — 같은 칸을 두 슬롯이 각자 매수. 의도한 명목의 2배가 쌓입니다
2. **교차 청산** — 교체 시 `flatten_position(ex, current.symbol)` 을 부르는데,
   같은 심볼이면 **다른 슬롯의 포지션까지 닫습니다.**
   그 슬롯은 자기 재고가 사라진 줄 모르고 매도 주문을 유지합니다

## 조치

### A. 교체 경로 — `taken_symbols` 인자 추가

```python
def maybe_rotate_slot(..., taken_symbols: set[str] | None = None):
    if taken_symbols:
        candidates = [c for c in candidates
                      if str(c.get("symbol")) not in taken_symbols]
```

호출부에서 다른 슬롯의 심볼을 모아 전달합니다.

### B. 신규 배정 경로 — 같은 구멍이 있었습니다

빈 슬롯에 심볼을 나눠줄 때 `selected[idx]` 로 인덱싱하는데,
**이미 채워진 슬롯의 심볼을 후보에서 빼지 않았습니다.**
후보 풀에서 보유 심볼을 먼저 제거하고, 빈 슬롯에만 순서대로 배정하도록 고쳤습니다.

### C. 회귀 테스트 5건

`tests/test_scalp_bot_e3_portfolio.py::SlotSymbolCollisionTests`

## 재시작 시 주의 — 손실컷이 즉시 재발동한다

손실컷 후 그대로 재개하면 기준자산이 옛 값(29.00)이라
현재 잔고(26.32)가 **-9.25%** 로 이미 문턱을 넘어 즉시 정지합니다.

```
--reset-baseline 필수
```

## 재시작 후 상태 (03:5x)

```
기준자산 26.3212 (리셋)
slot1 BEATUSDT 5x6  5칸 간격 2.11% 보유1 매수3 매도1
slot2 TUTUSDT  5x6  5칸 간격 2.11% 보유0 매수3
심볼 중복: 없음
```

**§23 의 촘촘한 프로파일도 함께 적용됐습니다** — 간격 4.26% -> **2.11%**.

## 함께 고친 것 — 사용자 수동 개입 대응

사용자가 수동으로 주문을 취소하거나 매매할 수 있다는 요구에 따라,
**슬롯마다 매 사이클 거래소와 대조**하도록 했습니다.

- `reconcile_cycle_state_with_exchange()` 가 이미 있었으나
  **단일 심볼 봇에서만 호출**되고 포트폴리오 봇에서는 안 쓰이고 있었습니다
- 포트폴리오 루프의 `process_live_fills` 직후에 연결했습니다
- `cancel_duplicates` / `cancel_stale` 은 **반드시 False** 로 둡니다.
  True 면 격자에 없는 주문을 취소하는데, 사용자의 수동 주문이 거기 해당합니다

### 그 과정에서 발견한 버그 — 조회 실패를 '주문 없음'으로 오인

`fetch_open_regular_orders()` 는 예외 시 **빈 목록**을 반환합니다.
그대로 대조하면 살아 있는 주문을 상태에서 지우고, 다음 사이클에 **중복 주문**을
냅니다. 증거금을 두 번 묶어 `-2019` 로 이어집니다.

**조회 실패 시 상태를 그대로 두도록** 고쳤습니다.

테스트: `E3ManualInterventionTests` 8건 (사용자 취소 / 수동 주문 보호 /
수량 불일치 무시 / 조회 실패 시 상태 보존 등)

## 테스트

```
880 passed, 26 subtests passed
```

---

# 25. E3 실패 원인 규명 및 수정 (2026-08-21 오전)

이틀 결과: **32.13 -> 24.34 (-24%)**. 백테스트는 3슬롯 10일 **+8.28%** 였습니다.

## 원인 — 전략이 아니라 운영이었습니다

원장 749건 이벤트 분해:

```
PLACE_ORDER_FAILED   461   <- 최다
PLACE_BUY            121
BUY_FILLED            39
SELL_FILLED            3   <- 완결 3건
강제 정리 계열        55   (LEGACY_FLAT 21 / RESUME_CLEAR 16 / SWITCH 14 / GLOBAL_STOP 4)
```

**격자 완결률 7.7%** (매수 39 / 매도 3).
그리드는 "싸게 사서 한 칸 위에 판다"가 전부인데 **파는 쪽이 실행되지 않았습니다.**

### 원인 1 — 재시작이 격자를 지웠다 (가장 큼)

`adopt_legacy_positions()` 는 **계좌의 미체결 주문을 전부 취소**합니다.
그 주문들이 곧 격자입니다. 이 함수는 `portfolio is None` 일 때만 불리는데,
**`--resume` 을 빼먹으면 그 경로로 들어갑니다.**

원장에 `LEGACY_ADOPT` 가 **22건**. 02:38~03:53 사이에만 12번입니다.
클로드와 코덱스가 각자 재시작하면서 여러 번 `--resume` 없이 띄웠습니다.

매 재시작마다:
1. 격자 주문 전부 취소 -> 격자 소멸
2. 보유 재고는 '레거시' 로 격리 -> **그 재고를 팔 격자가 없음**
3. 새 격자를 다른 가격대에 다시 깜 -> **또 사 모음**

**§17 에서 이미 기각한 '전량정리'(-11.48%)를 손으로 55번 실행한 셈입니다.**

### 원인 2 — 주문 실패 461건에 백오프가 없었다

전부 `-2019 Margin is insufficient`. 04:10~05:18 사이 1시간 동안
같은 주문을 8초마다 재시도했습니다. 격자에 구멍이 뚫린 채 돌았고,
매도가 걸릴 자리 자체가 없었습니다.

**증거금 부족은 재시도로 풀리지 않습니다.** 포지션이 정리되거나 가격이 움직여야 합니다.

### 원인 3 — 슬롯 심볼 중복 (§24 에서 수정 완료)

두 슬롯이 BEATUSDT 를 동시에 잡아 **-2.90**.

### 원인 4 — 회전 시간을 주지 않았다

격자 회전 중앙이 **270분(4.5시간)** 인데 평균 1시간마다 재시작했습니다.
**매도가 나올 시간 자체가 없었습니다.**

## 조치 A — `--resume` 을 기본값으로

```python
ap.add_argument("--resume", action="store_true", default=True)
ap.add_argument("--fresh-start", dest="resume", action="store_false")
```

이제 기본이 "이어받기" 이고, 새로 시작하려면 **`--fresh-start` 를 명시**해야 합니다.
사람이 실수할 여지를 없앴습니다.

테스트: `ResumeDefaultTests` 2건

## 조치 B — 주문 실패 백오프

`scripts/scalp_bot_e3.py`

```python
_BACKOFF_CODES = ("-2019", "-4131", "-1013")   # 증거금/유동성/최소수량
ORDER_BACKOFF_SEC = 300.0
```

- 이 코드로 실패하면 **그 칸을 5분간 쉽니다**
- 백오프 중에는 거래소를 **아예 호출하지 않습니다**
- 성공하면 백오프를 해제합니다
- **칸 단위**라 한 칸이 막혀도 다른 칸은 계속 돕니다
- `-1021`(타임스탬프) 같은 일시적 오류는 백오프하지 않습니다

테스트: `OrderBackoffTests` 7건

## 테스트

```
889 passed, 26 subtests passed
```

## 재시작 시 원칙 (사용자 질문에 대한 답)

**"어쩔 수 없이 재시작하면 기존 거래를 정리하지 말고 그냥 냅두는가?"**
-> **그렇습니다.** 미체결 주문이 격자이고, 보유 재고는 그 격자가 팔아야 할 물량입니다.
정리하면 §17 의 '전량정리'(-11.48%)가 됩니다.

이제 `--resume` 이 기본이라 별도 조치 없이 이어받습니다.
`reconcile_cycle_state_with_exchange`(§24)가 거래소 실제 주문과 대조해
사용자가 수동으로 취소한 것도 반영합니다.

## 남은 권고

- **`--capital-usage` 를 1.0 -> 0.8 로** 낮춰 증거금 여유를 두십시오.
  1.0 은 미체결 주문이 증거금을 선점해 `-2019` 를 부릅니다
- **최소 24시간 무개입 검증.** 회전 중앙 4.5시간이면 하루는 돌아야 표본이 생깁니다
- 관측은 텔레그램 브리핑으로만, **재시작 없이**

---

# 26. Codex 조치 — 보수형 2슬롯 2배 전환 (2026-08-21 오전)

사용자 요청:

- 슬롯 2개로 전환
- 매매 진행 시 총 자금 100% 운용
- 레버리지 격리 2배 고정
- `idle switch` 는 1800초와 비활성 중 판단

## 판단

`idle switch` 는 **임시 비활성보다 1800초 유지**로 판단했습니다.

근거:

- §22-4 에서 무체결 교체는 30분이 가장 나았습니다
- §24~§25 의 손실 원인은 idle 자체가 아니라 슬롯 중복, 재시작 격자 삭제,
  주문 실패 반복, 기준자산 손실컷 문제였습니다
- 다만 15분은 공격적이었으므로 30분으로 늦췄습니다

## 코드 변경

`scripts/scalp_bot_e3_portfolio.py`

- 기본 슬롯: `3 -> 2`
- 기본 레버리지: `3 -> 2`
- 기본 idle switch: `900초 -> 1800초`
- 포트폴리오 E3에서 `args.leverage != 2` 이면 기동 거부

`tests/test_scalp_bot_e3_portfolio.py`

- 보수형 기본값 테스트 추가
- 2배 외 레버리지 거부 테스트 추가

테스트:

```
tests.test_scalp_bot_e3_portfolio + tests.test_scalp_bot_e3
97 passed
```

## 재기동

재기동 직전 거래소 상태:

| 항목 | 값 |
|---|---|
| wallet | 24.341924 USDT |
| open orders | 0 |
| open positions | 0 |

과거 상태파일은 백업 후 `--fresh-start --reset-baseline` 으로 새로 시작했습니다.

기동 인자 핵심:

```powershell
--fresh-start
--reset-baseline
--slots 2
--leverage 2
--capital-usage 1.0
--idle-switch-sec 1800
--candidate-limit 100
```

재기동 후 상태:

| 항목 | 값 |
|---|---|
| PID | 13592 |
| open orders | 4 |
| open positions | 0 |
| slot1 | SANTOSUSDT 8x4 |
| slot2 | BTWUSDT 6x4 |
| 거래소 설정 | 두 심볼 모두 leverage 2, isolated True |

현재 주문은 각 슬롯당 매수 2개씩입니다. 아직 포지션은 없습니다.

# 27. Codex 조치 — 손실 기반 리밋 / 재시작 복원 / stale grid monitor (2026-08-21 10:39~10:49)

## 사용자 요청

- 손실 기반 리밋 여러 버전 검사
- 불필요한 미청산칸 주기 모니터링/정리
- 앱 문제 등으로 강제 재시작되면 기존 거래는 유지되고, 손실 리밋도 다시 걸려야 함

## 손실 리밋 검사 결과

거래소 income history 기준 오늘 순손익:

| 항목 | 값 |
|---|---:|
| REALIZED_PNL | -4.7244 |
| COMMISSION | -0.2022 |
| FUNDING_FEE | -0.0087 |
| NET | -4.9353 |

리밋 후보:

| 버전 | 기준 | 발동 | 판단 |
|---|---:|---|---|
| 15분 -0.15 | 매우 민감 | 02:07 ONGUSDT 소손실에도 발동 | 너무 자주 멈춤 |
| 15분 -0.25 | 민감 | 03:47 BEATUSDT 발동 | 가능 |
| 30분 -0.30 | 균형 | 03:47 BEATUSDT 발동 | 채택 |
| 30분 -0.50 | 완화 | 03:47 BEATUSDT 발동 | 늦음 |
| 60분 -0.60 | 누적 방어 | 03:47 BEATUSDT 발동 | 채택 |
| 60분 -1.00 | 느슨 | 03:47 BEATUSDT 발동 | 현재 자본엔 큼 |

최종 적용:

```powershell
--loss-guard-30m-usdt 0.30
--loss-guard-60m-usdt 0.60
--loss-guard-pause-sec 3600
--stale-buy-clear-sec 1800
```

중요: 손실 리밋은 전량손절기가 아니라 **신규 BUY 차단기**입니다.
발동 시 미체결 BUY만 취소하고, 보유칸의 reduceOnly SELL은 유지/복구합니다.

## 코드 변경

파일:

- `scripts/scalp_bot_e3_portfolio.py`
- `tests/test_scalp_bot_e3_portfolio.py`

추가/수정 내용:

- `PortfolioState.loss_pause_until`, `loss_guard_last_trigger_at` 추가
- 거래소 `futures_income_history`의 `REALIZED_PNL/COMMISSION/FUNDING_FEE`로 rolling 손실 리밋 계산
- 손실 리밋 발동 시 신규 매수/슬롯 교체 중단, 기존 SELL 유지
- `--resume` 시 loss pause 상태를 상태파일에서 복원
- stale grid monitor 추가
  - 거래소에 없는 stale/중복 주문 대조
  - 오래된 미체결 BUY 취소
  - 보유칸/SELL은 손실 청산하지 않음
- 포지션은 있는데 상태상 보유칸/SELL이 사라진 경우 `repair_orphan_position_held_rung()`으로 entry price 근처 rung 복원
- 범위 밖이어도 보유칸이 있으면 reduceOnly SELL 재등록 경로를 계속 타도록 수정
- `--resume`에서 슬롯 관리 심볼을 legacy 정리 대상에서 제외

테스트:

```powershell
.\.venv\Scripts\python.exe -m unittest tests.test_scalp_bot_e3_portfolio tests.test_scalp_bot_e3
104 passed
```

## 재시작 중 발견한 사고와 현재 상태

10:39 재시작 때 `--resume` 경로가 슬롯 보유 BTWUSDT를 legacy position으로 잘못 snapshot해
BTWUSDT 14개를 시장가 SELL로 정리했습니다. 이후 거래소에는 다시 BTWUSDT 포지션 14개가 확인됐고,
상태는 한동안 보유칸/SELL을 잃은 상태였습니다.

수정 후:

- BTWUSDT 중복 BUY `1618676802 @ 0.40838` 취소
- 상태파일의 BTWUSDT 보유 rung `[1]` 복원
- reduceOnly SELL 재등록 확인

현재 실행:

| 항목 | 값 |
|---|---|
| 실행 PID(부모) | 1412 |
| PID 파일 기준 실제 봇 PID | 9100 |
| 텔레그램 | `--no-telegram` 으로 실행 중 |
| wallet 확인값 | 약 24.51 USDT |
| open orders | 4 |
| open position | BTWUSDT 14개 |

현재 주문:

| 심볼 | 방향 | 가격 | 수량 | reduceOnly |
|---|---|---:|---:|---|
| BTWUSDT | SELL | 0.4250500 | 14 | True |
| BTWUSDT | BUY | 0.3917100 | 14 | False |
| SANTOSUSDT | BUY | 0.5062000 | 11.7 | False |
| SANTOSUSDT | BUY | 0.4784000 | 11.7 | False |

주의:

- 텔레그램 활성 상태로 재시작하면 초기 텔레그램 전송에서 멈추는 듯한 증상이 있어
  최종 실행은 `--no-telegram`으로 띄웠습니다.
- 다음 작업자는 텔레그램 timeout/비동기화 또는 시작 직후 알림 최소화를 별도 패치해야 합니다.
- PID 확인은 `logs/scalp_bot_e3_bot_pid.json` 기준으로 보십시오. Windows/venv 구조상 부모/자식 Python이 같이 보일 수 있습니다.

# 28. Codex 조치 — E3 정리 후 E2 수수료 보정 TP/SL 복구 (2026-08-21 10:50~10:58)

## 사용자 요청

`e2로 복구하고 수수료 계산을 해서 sl/tp 계산을 다시 하자`

## 먼저 한 정리

E3 잔여 충돌 방지를 위해 E3 프로세스를 중단하고 계좌를 비웠습니다.

정리 결과:

| 항목 | 처리 |
|---|---|
| E3 미체결 주문 | BTWUSDT 2건, SANTOSUSDT 2건 취소 |
| E3 잔여 포지션 | BTWUSDT LONG 14개 시장가 정리 |
| 정리 후 wallet | 24.55415959 USDT |
| 정리 후 open orders | 0 |
| 정리 후 positions | 0 |

주의: 처음 PowerShell에서 `CommandLine -like '*scalp_bot_e3_portfolio.py*'`로 정리하려다
현재 실행 중인 PowerShell 명령 자체가 매칭되어 끊겼습니다. Windows에서는 특정 PID 또는
PID 파일 기준으로만 종료해야 합니다.

## E2 수수료 보정

기존 E2:

```text
tp_rr = entry ± rr * gross_stop_risk
```

문제:

- 손절은 `가격 손실 + 왕복 수수료`
- 익절은 `가격 이익 - 왕복 수수료`
- 따라서 기존 `RR=2`는 순손익 기준 2:1이 아니었습니다

새 계산:

```text
gross_tp = rr * gross_stop_risk + (rr + 1) * roundtrip_fee_rate
```

예시(`roundtrip_fee_rate=0.001002`, `RR=2`, entry=100):

| gross stop risk | 기존 TP | 새 TP |
|---:|---:|---:|
| 0.35% | 100.7000 | 101.0006 |
| 0.50% | 101.0000 | 101.3006 |
| 1.00% | 102.0000 | 102.3006 |

BB 익절도 수수료 후 순익이 너무 작으면 비활성화합니다.

적용 파일:

- `scripts/scalp_bot_e2.py`
- `tests/test_scalp_bot_e2_fee_targets.py`

검증:

```powershell
.\.venv\Scripts\python.exe -m unittest tests.test_scalp_bot_e2_fee_targets tests.test_scalp_bot_e3_portfolio tests.test_scalp_bot_e3
108 passed
```

## 현재 E2 실행

실행 인자 핵심:

```powershell
--leverage 2
--symbols 85
--tranches 1
--rr 2.0
--roundtrip-fee-rate 0.001002
--min-net-tp-rate 0.0002
--min-risk-pct 0.35
--max-concurrency 2
--max-exposure 0.50
--base-balance 24.55415959
--i-know-it-loses
```

현재 상태:

| 항목 | 값 |
|---|---|
| E2 부모 PID | 14180 |
| E2 실제 PID 파일 | 10556 |
| E2 WS PID | 15304 |
| open orders | 0 |
| open positions | 0 |
| 상태파일 | `logs/scalp_bot_e2_state.json` 저장됨 |

주의:

- E2는 원래 검증상 마이너스 전략입니다. 이번 조치는 수수료 때문에 TP가 너무 가까웠던 문제를
  고친 것이지, 전략 우위를 새로 증명한 것이 아닙니다.
- 지금은 위험 축소를 위해 2배, 1차 진입, 최대 동시 2개, 자산 50% 노출로 제한했습니다.

---

## §26. e2 복귀 + 손절폭 확대 + 6슬롯 (2026-08-21 14:25)

사용자가 e3(그리드)를 접고 e2(EMA 눌림목)로 되돌린 뒤 요청한 4건을 처리했다.

### 26-1. "수수료만큼 TP를 올리자" -> 이미 되어 있었다 (변경 없음)

`fee_aware_rr_price()` 가 `gross_target = rr*risk + (rr+1)*fee` 로 이미 수수료를
TP 가격에 얹고 있다(scalp_bot_e2.py:104). BB 익절선도 `fee_aware_bb_price()` 가
수수료+최소순익을 못 넘으면 **아예 비활성화**한다. 그래서 8/21 BB 익절 14건이
전부 승리로 찍혔다 — 수수료 후 플러스가 보장된 선에서만 발동하기 때문이다.

### 26-2. 승률 지표의 함정 (기록 필수)

사용자가 "오늘 승률이 좋다"(48.4%)고 했으나 청산사유별로 보면:

| 사유 | 건수 | 승률 | 순익 |
|---|---|---|---|
| BB(익절) | 14 | 100.0% | +4.7120 |
| STOP_EXCHANGE(손절) | 17 | 5.9% | -2.8447 |

**동어반복이다.** 익절은 이익일 때만, 손절은 손실일 때만 발동하므로 e2 의
"승률"은 두 사유의 발동비율일 뿐 전략 정보가 없다. 게다가 오늘 순익 +1.8673 중
**ONGUSDT 한 종목이 +2.2363** — 그 종목을 빼면 -0.3690 으로 마이너스다.
t=0.89, 95% 구간 -0.0727~+0.1932 로 0을 포함한다.

판단은 이 셋으로만 한다: (1) 총명목 대비 수수료전 엣지 vs 수수료율
(누적 +0.0270% vs 0.0983% — 아직 4배 부족) (2) t값/신뢰구간 (3) 심볼별 분해.

### 26-3. --stop-widen-pct 신설 (기본값 0 = 기존 동작)

**발견:** `--min-risk-pct` 는 손절을 넓히는 값이 **아니라** 진입을 거르는
필터다(scalp_bot_e2.py:1616 — EMA25 가 가까우면 그 거래를 버린다).
손절선은 `stop = ind["e25"]` 고정이었고 넓히는 수단이 아예 없었다.

**근거(원장 130건):**
- 손절 28건 중 **50%가 진입 후 단 한 틱도 유리한 적 없음**(max_favorable 0.00%)
- 반대로 익절 102건의 **최대불리 ROE 중앙값 +0.00%** — 이긴 거래는 손절선
  근처에 가지도 않는다. -2% 밑으로 밀렸던 승리는 102건 중 **1건뿐**.
  -> 손절을 넓혀도 이긴 거래를 잃지 않는다.
- 실제 1분봉 재생(28건, 120분 관찰, 수수료 반영): 시험한 **모든** 확대폭이
  현재보다 나았다(-4.33 -> -3.60~-0.86). 단 -3%와 -5% 순서가 뒤집히는
  **비단조** -> 표본 28건으로 '방향'만 신뢰, 최적폭은 신뢰하지 않는다.

**구현:** `widened_stop(entry, stop, side, widen_pct)` — 넓히기 전용(이미 먼
EMA25 는 안 건드림). `min-risk-pct` 필터를 **통과한 뒤에** 적용해 진입 종목 수는
불변으로 뒀다(변수 하나만 바꿔야 효과를 잴 수 있다). 재시작 채택 경로에도 적용.
테스트 9건 추가(tests/test_scalp_e2_bugs.py).

**주의(단위):** 이 값은 **가격 %** 다. ROE 가 아니다. 2배에서 1.5% = ROE 3%.
재생 측정은 ROE 기준이었으므로 환산이 필요하다.

**검증:** 기동 직후 ZECUSDT 신호진입가 606.70 -> 손절 597.60 = 정확히 1.5%.

### 26-4. 슬롯 2 -> 6

`slots = min(int(bal*max_exposure // need_per_leg), max_concurrency)` 이므로
동시성만 올려선 안 되고 노출도 함께 올려야 한다. 잔고 26.14 기준:

| 동시 | 노출 | 실슬롯 | 슬롯당증거금 | 명목 |
|---|---|---|---|---|
| 2 | 0.50 | 2 | 6.54 | 13.07 |
| 6 | 0.75 | 6 | 3.27 | 6.54 |
| **6** | **0.80** | **6** | **3.49** | **6.97** |

0.80 채택(현금 20% 버퍼 유지). 명목 6.97 > 최소명목 5.6 이라 주문 통과.

### 26-5. WS / V2

- **WS 시장데이터: 정상** — 60초 5,174 메시지, 에러 0.
  (`avg_latency_ms 3862` 은 시계 offset -3858ms 의 아티팩트로 보인다)
- **V2: 플래그만 켰다(`WS_TRADE_USE_V2=true`). 체결워커는 안 띄웠다.**
  마지막 가동(8/19 21:3x) 로그가 **끊김없는 재접속 루프**였다 —
  `TimeoutError('timed out during opening handshake')` 가 15~45초마다 반복,
  연결 유지 실패. 그래서 status 의 `message_count_60s`가 0 이었다.
  즉 V2 는 "꺼둔 것"이 아니라 **이미 고장난 상태**였다.
- **e2 는 체결흐름(spike)을 아예 쓰지 않는다**(grep 결과 참조 0건).
  체결워커는 e2 거래에 영향이 없고 순수 데이터 수집용이다.
  -> 고장난 재접속 루프를 되살릴 실익이 없어 띄우지 않았다. 살리려면
  handshake timeout 원인부터 규명해야 한다(.env:876 "장기과제" 항목).

### 26-6. 기동 명령 (현재 실행중, PID 13496)

```
.venv/Scripts/python.exe scripts/scalp_bot_e2.py \
  --leverage 2 --symbols 85 --tranches 1 --rr 2.0 \
  --roundtrip-fee-rate 0.001002 --min-net-tp-rate 0.0002 \
  --min-risk-pct 0.35 --stop-widen-pct 1.5 --cooldown-sec 300 \
  --max-concurrency 6 --max-exposure 0.80 --min-leg-margin 3.0 \
  --max-unprotected-sec 120 --symbol-refresh-sec 1800 --brief-on-clock \
  --base-balance 24.55415959 --i-know-it-loses
```

배율은 사용자 지시로 **격리 2배 고정**(scalp_bot_e2.py:1697 에서 심볼마다
ISOLATED 설정). `--base-balance` 는 직전 값을 유지해 e2 재개 이후 누적
증감을 계속 볼 수 있게 했다(리셋 안 함).

### 26-7. 다음에 확인할 것

손절폭 1.5% 는 표본 28건에서 나온 **방향만 맞는** 값이다. 거래가 100건 이상
쌓이면 §26-2 의 세 지표로 이전 구간(손절 중앙값 0.97%)과 비교할 것.
특히 **수수료전 엣지가 0.0983% 를 넘는지**가 유일한 합격 기준이다.

---

## §27. e2 미니스윙 전환 — 볼밴 2차 + 목표수익 상향 (2026-08-21 15:0x)

### 27-1. e2 는 "볼밴+EMA" 가 아니다 (용어 정리)

볼밴은 **익절선 전용**이고 진입은 EMA 만 쓴다.

| 역할 | 기준 |
|---|---|
| 진입 | EMA 정배열(e5>e10>e15>e25) + 가격이 **e5 까지 눌림 터치** |
| 손절 | EMA25 (§26-3 이후 최소 1.5% 가격 바닥) |
| 익절 | **볼밴 상단**(롱)/하단(숏), 또는 손익비 2.0 |

### 27-2. TP/SL 의 ROI 실측 (원장 135건, 격리 2배)

| 청산 | 건수 | ROE 중앙 | 25~75% | 건당 순익 |
|---|---|---|---|---|
| 볼밴 익절 | 47 | **+2.11%** | +0.97~+4.54% | +0.1585 |
| 손익비 익절 | 7 | +2.44% | -0.32~+5.79% | +0.1648 |
| 손절(거래소) | 30 | **-1.93%** | -3.54~-1.18% | -0.1507 |
| 손절(EMA25) | 11 | -1.52% | -5.88~+1.89% | -0.0229 |
| 미상(외부청산) | 40 | -2.42% | -4.10~-1.23% | -0.1396 |

- 손익비 **1 : 1.15**, 손익분기 승률 46.4%, 실제 47.4% — 간신히 넘긴다
- 거래당 순익: 전체 **-0.0130 USDT(자산의 -0.050%)** / 오늘 **+0.0461(+0.176%)**
- 수수료 건당 0.0173 USDT = **ROE 0.20%** (왕복 0.1002% x 2배).
  볼밴 익절 ROE +2.11% 의 1/10 이라 수수료는 치명적이지 않다. 문제는 승률이다.
- **주의:** 위 금액은 슬롯 2개 시절(슬롯당 증거금 8.81) 값이다. 슬롯을 늘리면
  거래당 금액은 비례해 줄고 빈도가 는다. 금액이 아니라 **ROE 와 자산 %** 로 볼 것.

### 27-3. 보유시간 — 미니스윙과 거리가 멀었다

| 보유 | 0~5분 | 5~15분 | 15~20분 | 20분+ |
|---|---|---|---|---|
| 비중 | **61.5%** | 28.9% | **1.5%** | 8.1% |

중앙 **4.0분**. 볼밴 익절이 너무 빨리 걸린다.

### 27-4. --tranche2-band : 2차 진입을 볼린저 밴드에서

`tranche_targets()` 신설. 기본 [e5, e10, e15] 에서 **2차만 볼밴 반대편**으로
바꾼다(롱=하단, 숏=상단). 아래 두 경우엔 EMA10 으로 되돌린다(2차가 무의미):
1. 밴드가 1차(EMA5)보다 안쪽 -> 1차와 동시 체결
2. 밴드가 손절선(EMA25)보다 바깥 -> 닿기 전에 손절

**실측(정배열 45심볼):** 밴드 반대편은 진입가 대비 ROE 중앙 **-1.74%**,
손절선 -3.00% 안쪽. **68.9%** 의 경우 도달 가능.

**전제조건:** 이건 §26-3 의 손절 확대(1.5% 가격 = ROE 3.0%) 덕분이다.
확대 전 손절(실측 -1.93% ROE)이었다면 밴드(-1.74%)와 겹쳐 2차가 걸리기 전에
손절됐다. 손절을 되돌리면 이 로직도 같이 죽는다.

**성격:** 물타기다. 예전 "물타기 폐기" 결정과 겹치지만, 손절선이 -3.00% 에서
확실히 캡을 씌우므로 무한정 담는 그 방식과는 다르다. 사용자 인지 하에 진행.

### 27-5. --tp-extra-roe-pct : 목표수익 상향

`padded_tp()` 신설. 볼밴 익절선을 **ROE 기준** 지정한 만큼 더 멀리 민다.

**단위 주의:** 이건 **ROE %** 이고 `--stop-widen-pct` 는 **가격 %** 다.
사용자가 "목표 수익 %" 라고 할 때 기준이 ROE 이기 때문이다(볼밴 익절 ROE
중앙 +2.11%). 격리 2배면 ROE 0.5% = 가격 0.25%.

볼밴 익절 4개 지점 전부에 적용(신규진입 / 추가차수 / 재시작채택 /
진입전 '익절선통과' 사전검사). 사전검사를 빠뜨리면 늦춘 목표와 다른 선을 봐서
들어갈 자리를 놓친다.

### 27-6. 슬롯 6 -> 4 (최소명목 제약)

2차 분할을 넣으면 `need_per_leg` 가 차수배로 커진다. 잔고 26.14 기준:

| 차수 | 노출 | 동시 | 실슬롯 | 슬롯증거금 | 1차증거금 | 1차명목 |
|---|---|---|---|---|---|---|
| 1 | 0.80 | 6 | 6 | 3.49 | 3.49 | 6.97 |
| 2 | 0.80 | 6 | 3 | 6.97 | 3.49 | 6.97 |
| **2** | **0.95** | **4** | **4** | **6.21** | **3.10** | **6.21** |

사용자 선택: **4슬롯 x 2차 (노출 0.95)**. 익절선 정책은 "일단 그대로 두고 관찰".

**주의:** 노출 0.95 는 현금 버퍼가 1.30 USDT 뿐이다. 잔고가 조금만 줄어도
1차 명목이 최소명목 5.6 밑으로 떨어져 주문이 막힌다. 잔고 24 밑으로 내려가면
노출을 0.80 으로 낮추거나 차수를 1로 되돌릴 것.

### 27-7. 기동 명령 (현재 실행중, PID 15804)

```
.venv/Scripts/python.exe scripts/scalp_bot_e2.py \
  --leverage 2 --symbols 85 \
  --tranches 2 --tranche2-band --tp-extra-roe-pct 0.5 \
  --rr 2.0 --roundtrip-fee-rate 0.001002 --min-net-tp-rate 0.0002 \
  --min-risk-pct 0.35 --stop-widen-pct 1.5 --cooldown-sec 300 \
  --max-concurrency 4 --max-exposure 0.95 --min-leg-margin 3.0 \
  --max-unprotected-sec 120 --symbol-refresh-sec 1800 --brief-on-clock \
  --base-balance 24.55415959 --i-know-it-loses
```

기동 시 5건 채택, **전부 손절이 정확히 1.5%** 로 걸린 것을 확인
(ZEC 605.36->596.28, TRUMP/ACE/NEAR 모두 1.500%).

### 27-8. 다음에 확인할 것

한꺼번에 4가지를 바꿨다(손절확대 / 슬롯수 / 2차볼밴 / 목표수익). **어느 것이
효과였는지 분리되지 않는다.** 100건 이상 쌓이면 §26-2 의 세 지표로 본다:
1. 총명목 대비 **수수료전 엣지 vs 수수료율 0.0983%** (유일한 합격 기준)
2. 거래당 순익의 t값 / 95% 구간
3. 심볼별 분해 — 상위 1개를 빼도 플러스인지

추가로 이번 변경 전용 확인 항목:
- **보유시간 중앙값이 4.0분에서 얼마나 늘었나** (목표 15~20분)
- **2차 진입 체결률** — 볼밴까지 실제로 몇 % 나 도달하는가(예측 68.9%)
- **2차가 체결된 건의 승률**이 1차만 체결된 건보다 높은가 (물타기 검증)

---

## §28. 볼밴 진입 검증 + 2차 간격 실사고 (2026-08-21 15:2x)

사용자 질문: "볼밴으로도 진입 포인트 잡는건 어때 / EMA+볼밴 두개를 봐야해"

### 28-1. 결론: 볼밴 진입은 e2 를 수익으로 못 바꾼다

85심볼 10일 1분봉. 청산 규칙은 현재 라이브와 동일 고정(손절 1.5%가격 /
볼밴익절+ROE0.5% / 손익비2.0 / 최대240분), **진입만** 교체.
룩어헤드 방지: 신호는 봉 종가 판정, 진입은 **다음 봉 시가**.
라이브 가드 동일(진입가가 이미 손절선/익절선 밖이면 스킵, min-risk-pct 0.35).

| 진입 방식 | 거래수 | 승률 | 수수료전 | 수수료후 |
|---|---|---|---|---|
| 0 현행: 정배열+EMA5터치 | 25,722 | 56.2% | **-0.0140%** | -0.1142% |
| 1 정배열+볼밴하단터치 | 337 | 51.6% | **+0.0580%** | -0.0422% |
| 2 정배열+중심선터치 | 13,760 | 52.6% | -0.0222% | -0.1224% |
| 3 정배열+%B<=0.20 | **50** | 50.0% | +0.1343% | +0.0341% |
| 4 정배열+%B<=0.35 | 401 | 41.6% | -0.0381% | -0.1383% |
| 5 정배열+EMA5+%B<=0.50 | 2,139 | 44.0% | -0.0152% | -0.1154% |
| 6 정배열+EMA5+%B<=0.35 | 401 | 41.6% | -0.0381% | -0.1383% |
| 7 대조군: 볼밴하단만 | 13,640 | 44.4% | +0.0060% | -0.0942% |

**합격선은 수수료전 엣지 > 0.1002%(왕복수수료) 다. 넘는 게 없다.**
- #3 만 넘지만 **거래수 50건**이라 판단 불가(t값 계산 없이도 명백).
- #1(볼밴하단터치)은 현행보다 엣지가 **+0.072%p** 높지만 점추정 +0.0580% 로
  수수료 0.1002% 에 못 미친다. 즉 최선의 해석에서도 손실이다.
- 현행 진입은 이 기간 **수수료전이 이미 마이너스(-0.0140%)** 다. 승률 56.2%
  인데 엣지가 마이너스 = 이기는 거래가 작고 지는 거래가 크다.

### 28-2. EMA 정배열과 볼밴 하단은 구조적으로 양립하지 않는다

라이브 실측(85심볼, 정배열 66개):

| 조건 | 개수 | 비율 |
|---|---|---|
| EMA5 터치 | 47 | 71.2% |
| **볼밴 하단 터치** | **0** | **0.0%** |
| **둘 다** | **0** | **0.0%** |

%B(진입방향 기준) 중앙 **0.844**, %B<=0.35 인 심볼 **0개**.

정의상 당연하다 — EMA 정배열은 "상승 추세"이고 상승 추세면 가격이 볼밴
**상단**에 붙는다. 볼밴 하단은 과매도 구간이라 동시 성립이 거의 불가능하다.
**둘을 AND 로 묶으면 진입이 0건이 된다.** 백테스트 #1 이 337건뿐인 이유다.

쓸 수 있는 형태는 "동시"가 아니라 **"시간차"** 뿐이다 — 1차는 EMA5,
가격이 더 밀려 밴드에 닿으면 2차(§27-4). 이미 배포돼 있다.

### 28-3. [실사고] 2차가 1차와 같은 가격에 체결됐다

§27-4 배포 직후 실측:

| 심볼 | 1차 | 2차 | 간격 |
|---|---|---|---|
| LITUSDT | 2.739798 | 2.738500 | **0.047%** (ROE 0.095%) |
| AVAAIUSDT | 0.013492 | 0.013456 | 0.267% (ROE 0.534%) |

손절이 1.5%(ROE 3.0%)인데 2차가 0.15% 지점이면 **분할이 아니라 그냥 두 배로
한 번에 들어가는 것**이다. 원인: 볼밴이 손절선 밖이라 EMA10 으로 되돌아갔는데
추세장에서 EMA10 은 EMA5 바로 옆이다.

**수정:** `tranche_targets()` 재작성 + `--tranche-min-gap-pct` 신설.
2차 목표를 아래 순서로 정한다:
1. `--tranche2-band` 면 밴드(1차보다 깊을 때만)
2. `--tranche-min-gap-pct` 만큼은 1차에서 떨어뜨린다
3. 손절선(EMA25)을 넘으면 **1차~손절선의 80% 지점**으로 당긴다
   (예전처럼 EMA10 으로 되돌리면 위 실사고가 재발한다)
4. 그래도 1차보다 안쪽이면 **2차를 아예 두지 않는다**

적용값 **0.6%**(가격) = ROE 1.2%. 손절 1.5% 안쪽에 충분히 들어간다.

### 28-4. 기동 명령 (현재 실행중)

```
.venv/Scripts/python.exe scripts/scalp_bot_e2.py \
  --leverage 2 --symbols 85 \
  --tranches 2 --tranche2-band --tranche-min-gap-pct 0.6 \
  --tp-extra-roe-pct 0.5 \
  --rr 2.0 --roundtrip-fee-rate 0.001002 --min-net-tp-rate 0.0002 \
  --min-risk-pct 0.35 --stop-widen-pct 1.5 --cooldown-sec 300 \
  --max-concurrency 4 --max-exposure 0.95 --min-leg-margin 3.0 \
  --max-unprotected-sec 120 --symbol-refresh-sec 1800 --brief-on-clock \
  --base-balance 24.55415959 --i-know-it-loses
```

### 28-5. 남는 판단

백테스트는 e2 의 진입을 어떻게 바꿔도 수수료를 못 넘는다고 말한다. 이건
§26-2 의 누적 실측(수수료전 +0.0270% vs 수수료 0.0983%)과 방향이 같다.
**진입 신호를 손보는 축은 여기서 소진됐다고 본다.**

남은 축은 둘뿐이다:
1. **수수료를 낮춘다** — 메이커 지정가 진입(왕복 0.04% vs 0.1002%).
   합격선이 0.1002% -> 0.04% 로 내려가면 #1(+0.0580%)과 #7(+0.0060%)이
   비로소 플러스가 된다. **이게 유일하게 남은 실질적 경로로 보인다.**
2. **자본을 키운다** — 최소명목 5.0 제약이 풀리면 슬롯/분할 설계가 자유로워진다.

---

## §29. 메이커 전환 검증 + 익절 ROE 하한 (2026-08-21 16:xx)

사용자 요청: "메이커로 진입 시도 > 메이커로 매도 진행 / 체결 안될 경우 알아서
체결 시도도 지워야해 / 실 거래 수가 줄어드는지도 봐줘야해",
"수익도 ROI기준 3% 넘게 설정하면 얼마나 체류시간이 길어지는지"

### 29-1. 현재 e2 는 시장가 진입이다 (사실 확인)

`scalp_bot_e2.py:1791` -> `ex.open_market_position()` -> `exchange.py:447`
`type="MARKET"`. 청산도 `close_market_position`, 손절은 `STOP_MARKET`.

**원장 142건 실측 왕복 수수료율 0.0999%** (25~75% 0.0995~0.1003%)
= 테이커 왕복 0.1002% 와 일치. **양쪽 다 테이커**임이 확증됐다.

지정가 진입 기능은 `exchange.py:450 open_limit_position()` 과
`main.py:2937` 에 이미 있고 `.env LIMIT_ENTRY_ENABLED=true` 로 켜져 있으나
**e1 전용이고 e2 는 이 경로를 타지 않는다.**

주의: `open_limit_position` 은 `timeInForce="GTC"` 라 **메이커를 보장하지 않는다.**
확실히 메이커로 하려면 `GTX`(POST_ONLY) 가 필요한데 코드에 없다.

### 29-2. [결론] 메이커 진입 전환은 손해다

85심볼 10일. 메이커 0.0200% / 테이커 0.0501%(편도). 손절은 항상 마켓.

| 방식 | 대기 | 체결률 | 거래당 순익 | 현행 대비 |
|---|---|---|---|---|
| **현행 마켓+마켓** | - | 39.7% | **-0.0928%** | 기준 |
| 메이커진입+마켓청산 | 3봉 | 65.3% | -0.1350% | -0.0422%p |
| 양쪽 메이커 | 1봉 | 39.5% | -0.1177% | **-0.0249%p** |
| 양쪽 메이커 | 3봉 | 65.3% | -0.1171% | -0.0242%p |
| 양쪽 메이커 | 10봉 | 81.1% | -0.1228% | -0.0300%p |

**원인(30심볼 75,305건 실측):**

| | 값 |
|---|---|
| 마켓이 지정가보다 유리한 폭 | **평균 +0.1002%** (중앙 +0.0474%) |
| 마켓이 더 좋은 가격에 들어간 비율 | **58.0%** |
| 양쪽 메이커 수수료 절감 | +0.0602% |
| 차이 | **-0.04%p (손해)** |

가격이 EMA5 를 터치했다는 건 **계속 밀리고 있다**는 뜻이라 다음 봉 시가가
EMA5 보다 아래인 경우가 많다. 롱이면 시장가가 더 싸게 산다. 지정가는 정확히
EMA5 에서만 채워지므로 그 이득을 못 받는다.
**수수료로 아끼는 0.06% < 체결가에서 잃는 0.10%.**

기각된 가설: "마켓은 손절선을 넘으면 진입을 포기해서 급락을 거른다" ->
실제로 세보니 **포기 0건**이었다. 원인이 아니다.

### 29-3. 거래 빈도는 걸림돌이 아니었다

사용자 우려("실 거래 수가 줄어드는지")는 기우였다 — **오히려 늘어난다.**

| 대기 | 체결률 | 거래수(현행 대비) |
|---|---|---|
| 1봉 | 39.5% | **120.5%** |
| 3봉 | 65.3% | 114.6% |
| 10봉 | 81.1% | 101.4% |

지정가를 걸어두면 마켓이라면 놓쳤을 순간적 터치까지 잡는다.

### 29-4. [주의] 시뮬레이션 버그 — 같은 실수 반복 금지

1차 실행에서 메이커가 훨씬 나쁘게(-0.2016%) 나왔는데 **시뮬 버그**였다:
지정가를 걸고 **그 봉을 건너뛴 뒤** 다음 봉부터 체결을 검사해 신호봉의 터치를
통째로 놓쳤다. 마켓은 그 봉에서 터치를 잡으니 불공정했다.

교훈: **지정가는 신호봉 당일부터 살아 있어야 한다.** e5[i-1] 은 봉 i 시작 전에
이미 알 수 있는 값이므로 봉 i 에 주문이 얹혀 있는 게 맞다(룩어헤드 아님).

### 29-5. 익절 ROE 하한별 체류시간

| ROE 하한 | 거래수 | 보유 중앙 | 보유 평균 | 익절% | 손절% | 거래당 순익 |
|---|---|---|---|---|---|---|
| **0% (현행)** | 27,824 | **10분** | 25분 | 60.0% | 39.6% | -0.1061% |
| 2% | 26,752 | 11분 | 28분 | 56.5% | 43.1% | -0.1009% |
| **3%** | 23,143 | **14분** | 36분 | 50.2% | 49.0% | -0.0838% |
| 4% | 20,163 | 16분 | 43분 | 44.3% | 54.5% | -0.0861% |
| 5% | 17,819 | 18분 | 51분 | 39.7% | 58.5% | -0.0779% |
| 6% | 16,108 | **20분** | 57분 | 35.7% | 61.7% | -0.0724% |

**함정: "한 사이클 15~20분"이 되는 게 아니다.** 분포가 양극화된다.

| ROE 하한 | 0~5분 | 5~15분 | **15~20분** | 20~60분 | **60분+** |
|---|---|---|---|---|---|
| 0% | 30.6% | 30.2% | **7.6%** | 21.7% | **10.0%** |
| 3% | 23.7% | 28.0% | **7.6%** | 24.9% | **15.8%** |
| 6% | 18.6% | 24.0% | **7.2%** | 25.4% | **24.8%** |

15~20분 구간 비중은 오히려 **줄어든다**(7.6% -> 7.2%). 늘어나는 건 60분+
(10% -> 24.8%). 중앙값이 올라가는 건 긴 꼬리가 두꺼워져서다.
손절률도 39.6% -> 61.7% 로 오른다.

**방향은 좋다** — 목표를 올릴수록 거래당 손실이 준다(-0.1061% -> -0.0724%).
"너무 빨리 익절한다"는 직관이 데이터로 확인됐다. 하지만 t = -3.68 ~ -10.45 로
**유의하게 마이너스**라 이 축만으로는 흑자 전환이 안 된다.

### 29-6. 아직 안 끝난 것

**EMA5 보다 더 깊은 곳에 지정가를 거는 변형**(0.1~0.5% 아래)을 재는 중이다.
마켓이 이기는 이유가 "더 싸게 산다"이므로 지정가를 더 싼 곳에 걸면 뒤집힐 수
있다. 대신 체결률이 떨어진다. e1 설정의 `LIMIT_ENTRY_PULLBACK_PCT` 가 같은
개념이므로 예전에도 같은 문제를 만났던 것으로 보인다.

**코드는 아직 건드리지 않았다(측정만).** 라이브 e2 는 §28-4 설정 그대로다.

---

## §30. 3분봉 전환 + 진입 깊이 + 익절 ROE 하한 (2026-08-21 배포)

### 30-1. 측정 요약 — "더 깊이, 더 느리게"가 하나의 축이다

세 가지를 따로 쟀는데 전부 같은 방향을 가리켰다. 85심볼 10일, 거래당 순익(수수료 후).

**(A) 진입 깊이** (EMA 목표선에서 더 깊게)

| 깊이 | 마켓 거래당 | 현행 대비 | 거래수 |
|---|---|---|---|
| 0.0%(현행) | -0.0958% | 기준 | 100% |
| 0.3% | -0.0619% | +0.0339%p | 53% |
| **0.5%** | **-0.0482%** | **+0.0476%p** | 42% |

**(B) 진입 EMA 기간** (같은 축의 다른 표현)

| 진입선 | 거래당 | 거래수 |
|---|---|---|
| EMA5(현행) | -0.1039% | 28,064 |
| EMA15 | -0.0533% | 7,919 |
| EMA20 | **+0.0342%** | 1,625 (표본 적음) |

**(C) 신호봉 길이**

| 신호봉 | 거래당 | t | 보유 중앙 |
|---|---|---|---|
| 1분(현행) | -0.1025% | -10.61 | 10분 |
| 2분 | -0.0845% | -5.50 | 16분 |
| **3분** | **-0.0831%** | -4.86 | **20분** |
| 5분 | **-0.0417%** | -2.01 | 25분 |
| 10분 | -0.0481% | -1.74 | 39분 |

**(D) 익절 ROE 하한** — §29-5 참조. 하한 3%: 보유 14분, 거래당 -0.0838%.

### 30-2. 메이커보다 봉 길이가 효과가 크다

§29 의 메이커 전환은 깊이를 안 준 상태에서 **손해**였다(-0.0249%p).
깊이를 주면 메이커가 이긴다(깊이 0.5% 기준 +0.0709%p vs 마켓 +0.0476%p).
차이는 +0.023%p 뿐이고 주문 생애주기 관리가 필요해 리스크가 가장 크다.
**봉 길이(+0.019~0.061%p)가 더 크고 더 안전하다** — 그래서 이쪽을 먼저 했다.

### 30-3. 구현

**`--signal-tf-min N`** — `resample_bars()` 로 1분봉을 N분봉으로 합친다.

- **벽시계 경계로 묶는다**(00:00, 00:03...). 끝에서 N개씩 묶으면 매 분 경계가
  밀려 지표가 흔들린다. `open_time` 은 버킷 경계를 쓴다.
- **미완성 마지막 봉은 버린다** — get_klines 가 1분봉 미완성 캔들을 잘라내는
  것과 같은 원칙.
- **`klines_limit_for_tf()` 가 limit 을 200 이하로 묶는다.**
  WS 캔들 캐시가 1분봉 200개(ws_client.py MAX_LEN)라 이를 넘으면 REST 폴백이
  되고, 85심볼 x 매 사이클이면 예전 IP 밴 사고와 같은 경로가 된다.
  3분봉 = limit 123 -> 41봉(지표 최소 30봉 충족).
- **진입 경로와 재시작 채택 경로 둘 다** `signal_bars()` 를 쓴다. 한쪽만 바꾸면
  재시작 전후로 전략이 달라진다.

`.env INTERVAL` 은 **건드리지 않았다** — e1 과 WS 캐시가 공유하는 값이다.

**`--entry-depth-pct`** / **`--tp-floor-roe-pct`** 도 신설(둘 다 기본 0 = 기존 동작).

### 30-4. 기동 명령 (현재 실행중)

```
.venv/Scripts/python.exe scripts/scalp_bot_e2.py \
  --leverage 2 --symbols 85 --signal-tf-min 3 \
  --tranches 2 --tranche2-band --tranche-min-gap-pct 0.6 \
  --entry-depth-pct 0.5 --tp-floor-roe-pct 3.0 --tp-extra-roe-pct 0.5 \
  --rr 2.0 --roundtrip-fee-rate 0.001002 --min-net-tp-rate 0.0002 \
  --min-risk-pct 0.35 --stop-widen-pct 1.5 --cooldown-sec 300 \
  --max-concurrency 4 --max-exposure 0.95 --min-leg-margin 3.0 \
  --max-unprotected-sec 120 --symbol-refresh-sec 1800 --brief-on-clock \
  --base-balance 24.55415959 --i-know-it-loses
```

라이브 검증: 3분봉 41봉 생성, 지표 OK, 벽시계 경계 정렬 확인.
EMA25 가 1분봉 75457 -> 3분봉 75337 로 완만해졌다. 테스트 995건 통과.

### 30-5. 경고 — 변경이 겹쳐 있다

깊이 0.5% / 3분봉 / 익절하한 3% 는 **각각 따로 잰 값이라 단순히 더해지지 않는다.**
셋 다 "노이즈를 줄이고 더 깊이/느리게"라는 같은 방향이라 효과가 겹칠 가능성이 크다.
거래수도 각각 42% / 58% / 83% 로 줄어 곱하면 크게 줄 수 있다.

**2일 뒤 재평가할 것**(사용자 지시). 판단은 §26-2 세 지표로:
1. 총명목 대비 수수료전 엣지 vs 수수료 0.0983%
2. 거래당 순익의 t값 / 95% 구간
3. 심볼별 분해 — 상위 1개를 빼도 플러스인지

추가 확인: **실제 거래 빈도가 얼마나 줄었는지**. 너무 줄면 깊이를 0.3% 로
낮추거나 신호봉을 2분으로 되돌리는 게 첫 후보다.

---

## §31. 정각 설정 점검 브리핑 (2026-08-21)

사용자 요청: "1시간마다 모니터링 및 텔레그램 봇으로 지속 보고 / 3분봉과 마켓가로
진입 및 수수료 제외 순익이 +인지, 익절 하한 선택이 맞는지 EMA선택이 맞는지"

### 31-1. 기존 브리핑은 그대로

`--brief-on-clock` 이 이미 30분/정각에 텔레그램으로 보낸다:
잔고·기준대비, 구간별 전체/롱/숏 진입·청산·승률·순익, 보유중, 누적, 정합성 대조.
**여기는 안 건드렸다.**

### 31-2. `config_diag_text()` 신설 — 정각에만 추가 발송

**원장 전체가 아니라 이번 기동 이후만 본다**(`run_started_at` 기준).
설정이 다른 구간이 섞이면 판단이 오염된다(§30-5).
표본 5건 미만이면 "판단 불가"만 출력한다.

출력 4블록:

**[1] 합격선** — 수수료전 엣지 vs 수수료율. e2 의 유일한 합격 기준.
거래당 순익의 t값·95% 구간, 그리고 **1등 심볼을 빼도 플러스인지**.
(8/21 실측에서 하루 수익 전부가 ONGUSDT 하나였던 사고가 있었다 — §26-2)

**[2] 익절 하한 적절성** — 익절 ROE 중앙값 vs 설정 하한, 하한부근 건수.
중앙이 하한의 90% 미만이면 "하한이 안 먹고 있다" 경고.
손절 ROE 중앙 vs 설정값, 손익비와 손익분기승률 vs 실제 승률.

**[3] 진입선(EMA/깊이) 적절성** — 진입후 최대불리 ROE 중앙,
**"한번도 유리한 적 없음" 비율**. 45% 넘으면 "더 깊게" 경고.
(이 지표가 손절 확대의 근거였다 — §26-3에서 50%였다)

**[4] 신호봉·체결방식** — 보유 중앙(목표 15~20분), 시간당 거래수,
메이커 전환시 절감 여지 vs 현재 격차.

### 31-3. 실제 출력 예 (원장 40건으로 격리 검증)

```
── 설정 점검 (기동 후 4.1시간 / 40건) ──
  [1] 수수료전 엣지 +0.2461% vs 수수료 0.0963% -> 합격 (+0.1498%p)
      거래당 +0.0175 t=+0.49 [-0.0519~+0.0870] 0 포함(판단보류)
      1등 ONGUSDT 제외시 -0.2982 (뒤집힘) / 전체 +0.7017
  [2] 익절 21건 ROE중앙 +2.67% (하한 3.0%) 하한부근 5건
      주의: 익절 중앙이 하한보다 낮다 - 하한이 안 먹고 있다
      손절 19건 ROE중앙 -2.23% (설정 -3.0%)
      손익비 1:1.11 손익분기승률 47.3% vs 실제 52.5%
  [3] 진입선 깊이 0.5% / EMA5 기준
      진입후 최대불리 중앙 -0.19% / 한번도 유리한적 없음 9건 (22%)
  [4] 신호봉 3분 / 마켓진입
      보유중앙 7분 (목표 15~20분) / 시간당 9.7건
      메이커 전환시 절감 여지 0.0563%p (현재 격차 +0.1498%p)
```

**이 예시는 구설정 구간 원장이라 판정 자체는 무의미하다** — 형식 검증용이다.
"1등 제외시 뒤집힘"과 "하한이 안 먹고 있다"가 실제로 잡히는 걸 확인했다.

### 31-4. 읽는 법

- **[1] 이 미달이면 나머지는 볼 필요 없다.** 합격이어도 t값이 0을 포함하면 보류.
- **[1] 의 "1등 제외시 뒤집힘"이 뜨면 그 구간 성적은 믿지 말 것.**
- **[2] "하한이 안 먹고 있다"** = 볼밴 익절이 하한보다 먼저 걸린다 -> 하한을 올릴 여지.
- **[3] "한번도 유리한적 없음" 45%+** = 진입이 얕다 -> `--entry-depth-pct` 상향 검토.
- **[4] 보유중앙이 목표(15~20분)보다 짧으면** 신호봉을 5분으로 올리는 게 첫 후보.

### 31-5. 실패해도 브리핑은 살아 있다

`try/except` 로 감싸 점검이 터져도 `[설정점검 실패] {에러}` 만 보내고
본 브리핑과 봇은 계속 돈다.

---

## §32. E2 진입 직후 역행 컷 / MAE 조기 컷 (2026-08-22)

사용자 요청: "진입 직후 역행 필터와 MAE 기반 조기 컷 진행과 개선안 도출".

### 32-1. 최근 E2 손실 복기 근거

최근 실거래 E2 원장 97건 기준:

| 구간 | 건수 | 승률 | 순손익 | 수수료 |
| --- | ---: | ---: | ---: | ---: |
| MAE <= -3% ROE | 16 | 6.2% | -3.9299 | 0.1737 |
| MAE > -3% ROE | 81 | 53.1% | +3.0147 | 0.7618 |
| 보유 < 3분 | 19 | 31.6% | -1.5644 | 0.2067 |
| 보유 < 3분 손실 | 13 | 0.0% | -2.3148 | 0.1429 |
| 최고 ROE >= +1% | 52 | 80.8% | +7.4458 | 0.4898 |
| 최고 ROE < +1% | 45 | 4.4% | -8.3610 | 0.4457 |

결론: 손실의 핵심은 "진입 직후 바로 밀림"과 "한번도 유리하게 움직이지 못한 깊은 MAE"다.
TP/SL 목표값만 조정하는 것보다 조기 컷이 더 직접적이다.

### 32-2. 코드 반영

수정 파일:

- `scripts/scalp_bot_e2.py`
- `tests/test_scalp_bot_e2_fee_targets.py`

추가 함수:

- `early_cut_reason(...)`

추가 종료 사유:

- `EARLY_ADVERSE`: 진입 직후 역행 컷
- `MAE_CUT`: MAE 기반 조기 컷

기본값:

- `--early-adverse-sec 180`
- `--early-adverse-roe 1.5`
- `--early-adverse-min-favorable-roe 0.5`
- `--mae-cut-roe 3.0`
- `--mae-cut-grace-sec 180`
- `--mae-cut-min-favorable-roe 1.0`

둘 다 0 계열 인자로 비활성화 가능하다.

### 32-3. 의도와 한계

유리하게 움직였던 거래는 컷 대상에서 제외한다. `max_favorable_roe`가 충분했던 거래는 단순한
즉시 실패가 아니라 익절 후 반락/정상 되돌림일 수 있기 때문이다.

주의: 이건 원장 사후분석 기반의 보호장치다. 1초/틱 리플레이로 "정확히 이 가격에 잘랐으면
얼마가 개선됐는지"까지 확정한 것은 아니다. 다음 검증은 `EARLY_ADVERSE`, `MAE_CUT` 비중,
두 종료 사유의 평균 손실, 그리고 기존 `STOP_EMA25/STOP_EXCHANGE` 손실 감소 여부를 봐야 한다.

### 32-4. 검증

통과:

- `.\.venv\Scripts\python.exe -m unittest tests.test_scalp_bot_e2_fee_targets`
- `.\.venv\Scripts\python.exe -m py_compile scripts/scalp_bot_e2.py`

제한:

- `tests.test_scalp_e2_bugs`는 현재 venv에 `pytest`가 없어 `unittest` 로드 실패.
  코드 실패가 아니라 테스트 의존성 문제다.

---

## §33. E2 조기 컷 이후 수익 전환 판단 (2026-08-22)

사용자 질문: "개선로직으로 인해서 수익으로 전환이 돼?"

### 33-1. 결론

아직 "수익 전환된다"고 말하면 안 된다.

이번 개선은 수익을 키우는 알파 로직이 아니라 **손실을 빨리 줄이는 방어 로직**이다.
따라서 기대되는 1차 효과는 `STOP_EMA25/STOP_EXCHANGE`의 깊은 손실 축소이지,
`BB/RR` 수익 확대가 아니다.

### 33-2. 판단 근거

최근 E2 97건에서 손실 구간은 명확했다:

| 구간 | 건수 | 승률 | 순손익 |
| --- | ---: | ---: | ---: |
| MAE <= -3% | 16 | 6.2% | -3.9299 |
| MAE > -3% | 81 | 53.1% | +3.0147 |
| 최고 ROE < +1% | 45 | 4.4% | -8.3610 |
| 최고 ROE >= +1% | 52 | 80.8% | +7.4458 |

즉, 한 번도 제대로 유리하게 가지 못한 거래가 전체 손익을 깎았다.
`EARLY_ADVERSE`와 `MAE_CUT`은 이 구간을 겨냥한다.

### 33-3. 기대값 해석

| 항목 | 판단 |
| --- | --- |
| 손실 감소 가능성 | 높음 |
| 수수료 후 플러스 전환 | 미확정 |
| 이유 | 조기 컷은 손실을 줄이지만 승리 거래의 수익을 늘리지는 않음 |
| 필요한 표본 | 재가동 후 최소 30~50건 |

다음 검증 지표:

- `EARLY_ADVERSE`, `MAE_CUT` 평균 손실이 기존 `STOP_EMA25/STOP_EXCHANGE`보다 작아졌는지
- 조기 컷이 원래 `BB/RR`로 갈 거래를 잘못 잘라먹지 않는지
- 거래당 순익이 수수료 후 플러스로 바뀌는지
- 조기 컷 적용 후에도 1등 심볼 제외 손익이 플러스인지

### 33-4. 운영 상태

코드에는 반영됐다. 하지만 이 시점에는 봇을 재시작하지 않았다.

따라서 상태는:

- 코드 반영: 완료
- 단위 테스트: 완료
- 실전 적용: 재시작 전
- 수익 전환 검증: 미완료

실전 재가동 시 이 인자들이 기본값으로 켜진다:

- `--early-adverse-sec 180`
- `--early-adverse-roe 1.5`
- `--early-adverse-min-favorable-roe 0.5`
- `--mae-cut-roe 3.0`
- `--mae-cut-grace-sec 180`
- `--mae-cut-min-favorable-roe 1.0`
